//! MailingTrace trigger handlers
//!
//! Auto-generated by backbone-cli. Do not edit manually.

use std::sync::Arc;
use async_trait::async_trait;
use backbone_core::trigger::{
    ActionExecutor, TriggerContext, TriggerContextMut, TriggerEvent, TriggerHandler, TriggerRegistry,
};

use crate::domain::entity::MailingTrace;

pub type MailingTraceTriggerEvent      = TriggerEvent;
pub type MailingTraceTriggerContext    = TriggerContext<MailingTrace>;
pub type MailingTraceTriggerContextMut = TriggerContextMut<MailingTrace>;
pub type MailingTraceActionExecutor    = ActionExecutor;
pub type MailingTraceTriggerRegistry   = TriggerRegistry<MailingTrace>;
pub type MailingTraceTriggerHandlerObj =
    dyn TriggerHandler<TriggerContext<MailingTrace>, TriggerEvent>;

// State machine trigger handlers

/// Create a default registry pre-populated with all handlers for MailingTrace.
pub fn mailing_trace_trigger_registry() -> MailingTraceTriggerRegistry {
    TriggerRegistry::build(|r| {
    })
}
