//! Mailing trigger handlers
//!
//! Auto-generated by backbone-cli. Do not edit manually.

use std::sync::Arc;
use async_trait::async_trait;
use backbone_core::trigger::{
    ActionExecutor, TriggerContext, TriggerContextMut, TriggerEvent, TriggerHandler, TriggerRegistry,
};

use crate::domain::entity::Mailing;

pub type MailingTriggerEvent      = TriggerEvent;
pub type MailingTriggerContext    = TriggerContext<Mailing>;
pub type MailingTriggerContextMut = TriggerContextMut<Mailing>;
pub type MailingActionExecutor    = ActionExecutor;
pub type MailingTriggerRegistry   = TriggerRegistry<Mailing>;
pub type MailingTriggerHandlerObj =
    dyn TriggerHandler<TriggerContext<Mailing>, TriggerEvent>;

// State machine trigger handlers

/// Create a default registry pre-populated with all handlers for Mailing.
pub fn mailing_trigger_registry() -> MailingTriggerRegistry {
    TriggerRegistry::build(|r| {
    })
}
