//! MailingAbTest DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::MailingAbTest;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::AbWinnerSelection;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new MailingAbTest
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateMailingAbTestDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "campaign_id")]
    pub campaign_id: Uuid,
    #[serde(alias = "winner_selection")]
    pub winner_selection: AbWinnerSelection,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "winner_selection_sms")]
    pub winner_selection_sms: Option<AbWinnerSelection>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "promote_at")]
    pub promote_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub completed: bool,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "winner_mailing_id")]
    pub winner_mailing_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 64)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "sampling_seed")]
    pub sampling_seed: String,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a MailingAbTest
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateMailingAbTestDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "campaign_id")]
    pub campaign_id: Uuid,
    #[serde(alias = "winner_selection")]
    pub winner_selection: AbWinnerSelection,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "winner_selection_sms")]
    pub winner_selection_sms: Option<AbWinnerSelection>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "promote_at")]
    pub promote_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub completed: bool,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "winner_mailing_id")]
    pub winner_mailing_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 64)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "sampling_seed")]
    pub sampling_seed: String,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a MailingAbTest
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchMailingAbTestDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "campaign_id")]
    pub campaign_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "winner_selection")]
    pub winner_selection: Option<AbWinnerSelection>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "winner_selection_sms")]
    pub winner_selection_sms: Option<AbWinnerSelection>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "promote_at")]
    pub promote_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub completed: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "winner_mailing_id")]
    pub winner_mailing_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 64)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "sampling_seed")]
    pub sampling_seed: Option<String>,
}

impl PatchMailingAbTestDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.campaign_id.is_some() || self.winner_selection.is_some() || self.winner_selection_sms.is_some() || self.promote_at.is_some() || self.completed.is_some() || self.winner_mailing_id.is_some() || self.sampling_seed.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for MailingAbTest entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct MailingAbTestResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub campaign_id: Uuid,
    pub winner_selection: AbWinnerSelection,
    pub winner_selection_sms: Option<AbWinnerSelection>,
    pub promote_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub completed: bool,
    pub winner_mailing_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub sampling_seed: String,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for MailingAbTest entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct MailingAbTestListResponseDto {
    /// List of items
    pub items: Vec<MailingAbTestResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl MailingAbTestListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<MailingAbTestResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct MailingAbTestSummaryDto {
    pub id: Uuid,
    pub campaign_id: Uuid,
    pub winner_selection: AbWinnerSelection,
    pub winner_selection_sms: Option<AbWinnerSelection>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<MailingAbTest> for MailingAbTestResponseDto {
    fn from(entity: MailingAbTest) -> Self {
        Self {
            id: entity.id,
            campaign_id: entity.campaign_id,
            winner_selection: entity.winner_selection,
            winner_selection_sms: entity.winner_selection_sms,
            promote_at: entity.promote_at,
            completed: entity.completed,
            winner_mailing_id: entity.winner_mailing_id,
            sampling_seed: entity.sampling_seed,
            metadata: entity.metadata,
        }
    }
}

impl From<MailingAbTest> for MailingAbTestSummaryDto {
    fn from(entity: MailingAbTest) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            campaign_id: entity.campaign_id,
            winner_selection: entity.winner_selection,
            winner_selection_sms: entity.winner_selection_sms,
            created_at,
        }
    }
}

impl From<CreateMailingAbTestDto> for MailingAbTest {
    fn from(dto: CreateMailingAbTestDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            campaign_id: dto.campaign_id,
            winner_selection: dto.winner_selection,
            winner_selection_sms: dto.winner_selection_sms,
            promote_at: dto.promote_at,
            completed: dto.completed,
            winner_mailing_id: dto.winner_mailing_id,
            sampling_seed: dto.sampling_seed,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&MailingAbTest> for MailingAbTestResponseDto {
    fn from(entity: &MailingAbTest) -> Self {
        Self {
            id: entity.id.clone(),
            campaign_id: entity.campaign_id.clone(),
            winner_selection: entity.winner_selection.clone(),
            winner_selection_sms: entity.winner_selection_sms.clone(),
            promote_at: entity.promote_at.clone(),
            completed: entity.completed.clone(),
            winner_mailing_id: entity.winner_mailing_id.clone(),
            sampling_seed: entity.sampling_seed.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateMailingAbTestDto> for MailingAbTest {
    fn from_create_dto(dto: CreateMailingAbTestDto) -> backbone_core::ServiceResult<Self> {
        Ok(MailingAbTest::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateMailingAbTestDto> for MailingAbTest {
    fn apply_update(mut self, dto: UpdateMailingAbTestDto) -> backbone_core::ServiceResult<Self> {
        self.campaign_id = dto.campaign_id;
        self.winner_selection = dto.winner_selection;
        self.winner_selection_sms = dto.winner_selection_sms;
        self.promote_at = dto.promote_at;
        self.completed = dto.completed;
        self.winner_mailing_id = dto.winner_mailing_id;
        self.sampling_seed = dto.sampling_seed;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to MailingAbTest here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
