//! MailingFilter DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::MailingFilter;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::MailingTargetModel;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new MailingFilter
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateMailingFilterDto {
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[serde(alias = "target_model")]
    pub target_model: MailingTargetModel,
    pub domain: serde_json::Value,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a MailingFilter
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateMailingFilterDto {
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[serde(alias = "target_model")]
    pub target_model: MailingTargetModel,
    pub domain: serde_json::Value,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a MailingFilter
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchMailingFilterDto {
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "target_model")]
    pub target_model: Option<MailingTargetModel>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub domain: Option<serde_json::Value>,
}

impl PatchMailingFilterDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.name.is_some() || self.target_model.is_some() || self.domain.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for MailingFilter entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct MailingFilterResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    pub target_model: MailingTargetModel,
    pub domain: serde_json::Value,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for MailingFilter entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct MailingFilterListResponseDto {
    /// List of items
    pub items: Vec<MailingFilterResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl MailingFilterListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<MailingFilterResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct MailingFilterSummaryDto {
    pub id: Uuid,
    pub name: String,
    pub target_model: MailingTargetModel,
    pub domain: serde_json::Value,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<MailingFilter> for MailingFilterResponseDto {
    fn from(entity: MailingFilter) -> Self {
        Self {
            id: entity.id,
            name: entity.name,
            target_model: entity.target_model,
            domain: entity.domain,
            metadata: entity.metadata,
        }
    }
}

impl From<MailingFilter> for MailingFilterSummaryDto {
    fn from(entity: MailingFilter) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            name: entity.name,
            target_model: entity.target_model,
            domain: entity.domain,
            created_at,
        }
    }
}

impl From<CreateMailingFilterDto> for MailingFilter {
    fn from(dto: CreateMailingFilterDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            name: dto.name,
            target_model: dto.target_model,
            domain: dto.domain,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&MailingFilter> for MailingFilterResponseDto {
    fn from(entity: &MailingFilter) -> Self {
        Self {
            id: entity.id.clone(),
            name: entity.name.clone(),
            target_model: entity.target_model.clone(),
            domain: entity.domain.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateMailingFilterDto> for MailingFilter {
    fn from_create_dto(dto: CreateMailingFilterDto) -> backbone_core::ServiceResult<Self> {
        Ok(MailingFilter::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateMailingFilterDto> for MailingFilter {
    fn apply_update(mut self, dto: UpdateMailingFilterDto) -> backbone_core::ServiceResult<Self> {
        self.name = dto.name;
        self.target_model = dto.target_model;
        self.domain = dto.domain;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to MailingFilter here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
