//! MailingTrace DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::MailingTrace;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::TraceFailureType;
use crate::domain::entity::TraceStatus;
use crate::domain::entity::TraceType;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new MailingTrace
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateMailingTraceDto {
    #[serde(alias = "trace_type")]
    pub trace_type: TraceType,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_test_trace")]
    pub is_test_trace: bool,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "mailing_id")]
    pub mailing_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "campaign_id")]
    pub campaign_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 64)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "recipient_model")]
    pub recipient_model: String,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "recipient_id")]
    pub recipient_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 255)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "recipient_email")]
    pub recipient_email: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "mail_id")]
    pub mail_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 255)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "message_id")]
    pub message_id: Option<String>,
    #[serde(alias = "trace_status")]
    pub trace_status: TraceStatus,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "failure_type")]
    pub failure_type: Option<TraceFailureType>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "failure_reason")]
    pub failure_reason: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "sent_datetime")]
    pub sent_datetime: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "open_datetime")]
    pub open_datetime: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "reply_datetime")]
    pub reply_datetime: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "links_click_datetime")]
    pub links_click_datetime: Option<DateTime<Utc>>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a MailingTrace
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateMailingTraceDto {
    #[serde(alias = "trace_type")]
    pub trace_type: TraceType,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_test_trace")]
    pub is_test_trace: bool,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "mailing_id")]
    pub mailing_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "campaign_id")]
    pub campaign_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 64)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "recipient_model")]
    pub recipient_model: String,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "recipient_id")]
    pub recipient_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 255)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "recipient_email")]
    pub recipient_email: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "mail_id")]
    pub mail_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 255)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "message_id")]
    pub message_id: Option<String>,
    #[serde(alias = "trace_status")]
    pub trace_status: TraceStatus,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "failure_type")]
    pub failure_type: Option<TraceFailureType>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "failure_reason")]
    pub failure_reason: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "sent_datetime")]
    pub sent_datetime: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "open_datetime")]
    pub open_datetime: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "reply_datetime")]
    pub reply_datetime: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "links_click_datetime")]
    pub links_click_datetime: Option<DateTime<Utc>>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a MailingTrace
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchMailingTraceDto {
    #[serde(skip_serializing_if = "Option::is_none", alias = "trace_type")]
    pub trace_type: Option<TraceType>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "is_test_trace")]
    pub is_test_trace: Option<bool>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "mailing_id")]
    pub mailing_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "campaign_id")]
    pub campaign_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 64)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "recipient_model")]
    pub recipient_model: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "recipient_id")]
    pub recipient_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 255)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "recipient_email")]
    pub recipient_email: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "mail_id")]
    pub mail_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 255)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "message_id")]
    pub message_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "trace_status")]
    pub trace_status: Option<TraceStatus>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "failure_type")]
    pub failure_type: Option<TraceFailureType>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "failure_reason")]
    pub failure_reason: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "sent_datetime")]
    pub sent_datetime: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "open_datetime")]
    pub open_datetime: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "reply_datetime")]
    pub reply_datetime: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "links_click_datetime")]
    pub links_click_datetime: Option<DateTime<Utc>>,
}

impl PatchMailingTraceDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.trace_type.is_some() || self.is_test_trace.is_some() || self.mailing_id.is_some() || self.campaign_id.is_some() || self.recipient_model.is_some() || self.recipient_id.is_some() || self.recipient_email.is_some() || self.mail_id.is_some() || self.message_id.is_some() || self.trace_status.is_some() || self.failure_type.is_some() || self.failure_reason.is_some() || self.sent_datetime.is_some() || self.open_datetime.is_some() || self.reply_datetime.is_some() || self.links_click_datetime.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for MailingTrace entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct MailingTraceResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    pub trace_type: TraceType,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_test_trace: bool,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub mailing_id: Uuid,
    pub campaign_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub recipient_model: String,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub recipient_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub recipient_email: String,
    pub mail_id: Option<Uuid>,
    pub message_id: Option<String>,
    pub trace_status: TraceStatus,
    pub failure_type: Option<TraceFailureType>,
    pub failure_reason: Option<String>,
    pub sent_datetime: Option<DateTime<Utc>>,
    pub open_datetime: Option<DateTime<Utc>>,
    pub reply_datetime: Option<DateTime<Utc>>,
    pub links_click_datetime: Option<DateTime<Utc>>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for MailingTrace entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct MailingTraceListResponseDto {
    /// List of items
    pub items: Vec<MailingTraceResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl MailingTraceListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<MailingTraceResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct MailingTraceSummaryDto {
    pub id: Uuid,
    pub trace_type: TraceType,
    pub is_test_trace: bool,
    pub mailing_id: Uuid,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<MailingTrace> for MailingTraceResponseDto {
    fn from(entity: MailingTrace) -> Self {
        Self {
            id: entity.id,
            trace_type: entity.trace_type,
            is_test_trace: entity.is_test_trace,
            mailing_id: entity.mailing_id,
            campaign_id: entity.campaign_id,
            recipient_model: entity.recipient_model,
            recipient_id: entity.recipient_id,
            recipient_email: entity.recipient_email,
            mail_id: entity.mail_id,
            message_id: entity.message_id,
            trace_status: entity.trace_status,
            failure_type: entity.failure_type,
            failure_reason: entity.failure_reason,
            sent_datetime: entity.sent_datetime,
            open_datetime: entity.open_datetime,
            reply_datetime: entity.reply_datetime,
            links_click_datetime: entity.links_click_datetime,
            metadata: entity.metadata,
        }
    }
}

impl From<MailingTrace> for MailingTraceSummaryDto {
    fn from(entity: MailingTrace) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            trace_type: entity.trace_type,
            is_test_trace: entity.is_test_trace,
            mailing_id: entity.mailing_id,
            created_at,
        }
    }
}

impl From<CreateMailingTraceDto> for MailingTrace {
    fn from(dto: CreateMailingTraceDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            trace_type: dto.trace_type,
            is_test_trace: dto.is_test_trace,
            mailing_id: dto.mailing_id,
            campaign_id: dto.campaign_id,
            recipient_model: dto.recipient_model,
            recipient_id: dto.recipient_id,
            recipient_email: dto.recipient_email,
            mail_id: dto.mail_id,
            message_id: dto.message_id,
            trace_status: dto.trace_status,
            failure_type: dto.failure_type,
            failure_reason: dto.failure_reason,
            sent_datetime: dto.sent_datetime,
            open_datetime: dto.open_datetime,
            reply_datetime: dto.reply_datetime,
            links_click_datetime: dto.links_click_datetime,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&MailingTrace> for MailingTraceResponseDto {
    fn from(entity: &MailingTrace) -> Self {
        Self {
            id: entity.id.clone(),
            trace_type: entity.trace_type.clone(),
            is_test_trace: entity.is_test_trace.clone(),
            mailing_id: entity.mailing_id.clone(),
            campaign_id: entity.campaign_id.clone(),
            recipient_model: entity.recipient_model.clone(),
            recipient_id: entity.recipient_id.clone(),
            recipient_email: entity.recipient_email.clone(),
            mail_id: entity.mail_id.clone(),
            message_id: entity.message_id.clone(),
            trace_status: entity.trace_status.clone(),
            failure_type: entity.failure_type.clone(),
            failure_reason: entity.failure_reason.clone(),
            sent_datetime: entity.sent_datetime.clone(),
            open_datetime: entity.open_datetime.clone(),
            reply_datetime: entity.reply_datetime.clone(),
            links_click_datetime: entity.links_click_datetime.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateMailingTraceDto> for MailingTrace {
    fn from_create_dto(dto: CreateMailingTraceDto) -> backbone_core::ServiceResult<Self> {
        Ok(MailingTrace::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateMailingTraceDto> for MailingTrace {
    fn apply_update(mut self, dto: UpdateMailingTraceDto) -> backbone_core::ServiceResult<Self> {
        self.trace_type = dto.trace_type;
        self.is_test_trace = dto.is_test_trace;
        self.mailing_id = dto.mailing_id;
        self.campaign_id = dto.campaign_id;
        self.recipient_model = dto.recipient_model;
        self.recipient_id = dto.recipient_id;
        self.recipient_email = dto.recipient_email;
        self.mail_id = dto.mail_id;
        self.message_id = dto.message_id;
        self.trace_status = dto.trace_status;
        self.failure_type = dto.failure_type;
        self.failure_reason = dto.failure_reason;
        self.sent_datetime = dto.sent_datetime;
        self.open_datetime = dto.open_datetime;
        self.reply_datetime = dto.reply_datetime;
        self.links_click_datetime = dto.links_click_datetime;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to MailingTrace here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
