//! MailingSubscription DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::MailingSubscription;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new MailingSubscription
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateMailingSubscriptionDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "contact_id")]
    pub contact_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "mailing_audience_id")]
    pub mailing_audience_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "opt_out")]
    pub opt_out: bool,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "opt_out_datetime")]
    pub opt_out_datetime: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "opt_out_reason_id")]
    pub opt_out_reason_id: Option<Uuid>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a MailingSubscription
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateMailingSubscriptionDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "contact_id")]
    pub contact_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "mailing_audience_id")]
    pub mailing_audience_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "opt_out")]
    pub opt_out: bool,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "opt_out_datetime")]
    pub opt_out_datetime: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "opt_out_reason_id")]
    pub opt_out_reason_id: Option<Uuid>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a MailingSubscription
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchMailingSubscriptionDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "contact_id")]
    pub contact_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "mailing_audience_id")]
    pub mailing_audience_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "opt_out")]
    pub opt_out: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "opt_out_datetime")]
    pub opt_out_datetime: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "opt_out_reason_id")]
    pub opt_out_reason_id: Option<Uuid>,
}

impl PatchMailingSubscriptionDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.contact_id.is_some() || self.mailing_audience_id.is_some() || self.opt_out.is_some() || self.opt_out_datetime.is_some() || self.opt_out_reason_id.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for MailingSubscription entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct MailingSubscriptionResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub contact_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub mailing_audience_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub opt_out: bool,
    pub opt_out_datetime: Option<DateTime<Utc>>,
    pub opt_out_reason_id: Option<Uuid>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for MailingSubscription entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct MailingSubscriptionListResponseDto {
    /// List of items
    pub items: Vec<MailingSubscriptionResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl MailingSubscriptionListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<MailingSubscriptionResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct MailingSubscriptionSummaryDto {
    pub id: Uuid,
    pub contact_id: Uuid,
    pub mailing_audience_id: Uuid,
    pub opt_out: bool,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<MailingSubscription> for MailingSubscriptionResponseDto {
    fn from(entity: MailingSubscription) -> Self {
        Self {
            id: entity.id,
            contact_id: entity.contact_id,
            mailing_audience_id: entity.mailing_audience_id,
            opt_out: entity.opt_out,
            opt_out_datetime: entity.opt_out_datetime,
            opt_out_reason_id: entity.opt_out_reason_id,
            metadata: entity.metadata,
        }
    }
}

impl From<MailingSubscription> for MailingSubscriptionSummaryDto {
    fn from(entity: MailingSubscription) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            contact_id: entity.contact_id,
            mailing_audience_id: entity.mailing_audience_id,
            opt_out: entity.opt_out,
            created_at,
        }
    }
}

impl From<CreateMailingSubscriptionDto> for MailingSubscription {
    fn from(dto: CreateMailingSubscriptionDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            contact_id: dto.contact_id,
            mailing_audience_id: dto.mailing_audience_id,
            opt_out: dto.opt_out,
            opt_out_datetime: dto.opt_out_datetime,
            opt_out_reason_id: dto.opt_out_reason_id,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&MailingSubscription> for MailingSubscriptionResponseDto {
    fn from(entity: &MailingSubscription) -> Self {
        Self {
            id: entity.id.clone(),
            contact_id: entity.contact_id.clone(),
            mailing_audience_id: entity.mailing_audience_id.clone(),
            opt_out: entity.opt_out.clone(),
            opt_out_datetime: entity.opt_out_datetime.clone(),
            opt_out_reason_id: entity.opt_out_reason_id.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateMailingSubscriptionDto> for MailingSubscription {
    fn from_create_dto(dto: CreateMailingSubscriptionDto) -> backbone_core::ServiceResult<Self> {
        Ok(MailingSubscription::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateMailingSubscriptionDto> for MailingSubscription {
    fn apply_update(mut self, dto: UpdateMailingSubscriptionDto) -> backbone_core::ServiceResult<Self> {
        self.contact_id = dto.contact_id;
        self.mailing_audience_id = dto.mailing_audience_id;
        self.opt_out = dto.opt_out;
        self.opt_out_datetime = dto.opt_out_datetime;
        self.opt_out_reason_id = dto.opt_out_reason_id;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to MailingSubscription here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
