//! MailingContact DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::MailingContact;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new MailingContact
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateMailingContactDto {
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "first_name")]
    pub first_name: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "last_name")]
    pub last_name: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 255)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub email: String,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "company_name")]
    pub company_name: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 2)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "country_code")]
    pub country_code: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 64)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub phone: Option<String>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a MailingContact
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateMailingContactDto {
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "first_name")]
    pub first_name: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "last_name")]
    pub last_name: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 255)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub email: String,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "company_name")]
    pub company_name: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 2)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "country_code")]
    pub country_code: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 64)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub phone: Option<String>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a MailingContact
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchMailingContactDto {
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "first_name")]
    pub first_name: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "last_name")]
    pub last_name: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 255)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_name")]
    pub company_name: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 2)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "country_code")]
    pub country_code: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 64)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub phone: Option<String>,
}

impl PatchMailingContactDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.name.is_some() || self.first_name.is_some() || self.last_name.is_some() || self.email.is_some() || self.company_name.is_some() || self.country_code.is_some() || self.phone.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for MailingContact entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct MailingContactResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    pub name: Option<String>,
    pub first_name: Option<String>,
    pub last_name: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub email: String,
    pub company_name: Option<String>,
    pub country_code: Option<String>,
    pub phone: Option<String>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for MailingContact entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct MailingContactListResponseDto {
    /// List of items
    pub items: Vec<MailingContactResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl MailingContactListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<MailingContactResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct MailingContactSummaryDto {
    pub id: Uuid,
    pub name: Option<String>,
    pub first_name: Option<String>,
    pub last_name: Option<String>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<MailingContact> for MailingContactResponseDto {
    fn from(entity: MailingContact) -> Self {
        Self {
            id: entity.id,
            name: entity.name,
            first_name: entity.first_name,
            last_name: entity.last_name,
            email: entity.email,
            company_name: entity.company_name,
            country_code: entity.country_code,
            phone: entity.phone,
            metadata: entity.metadata,
        }
    }
}

impl From<MailingContact> for MailingContactSummaryDto {
    fn from(entity: MailingContact) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            name: entity.name,
            first_name: entity.first_name,
            last_name: entity.last_name,
            created_at,
        }
    }
}

impl From<CreateMailingContactDto> for MailingContact {
    fn from(dto: CreateMailingContactDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            name: dto.name,
            first_name: dto.first_name,
            last_name: dto.last_name,
            email: dto.email,
            company_name: dto.company_name,
            country_code: dto.country_code,
            phone: dto.phone,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&MailingContact> for MailingContactResponseDto {
    fn from(entity: &MailingContact) -> Self {
        Self {
            id: entity.id.clone(),
            name: entity.name.clone(),
            first_name: entity.first_name.clone(),
            last_name: entity.last_name.clone(),
            email: entity.email.clone(),
            company_name: entity.company_name.clone(),
            country_code: entity.country_code.clone(),
            phone: entity.phone.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateMailingContactDto> for MailingContact {
    fn from_create_dto(dto: CreateMailingContactDto) -> backbone_core::ServiceResult<Self> {
        Ok(MailingContact::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateMailingContactDto> for MailingContact {
    fn apply_update(mut self, dto: UpdateMailingContactDto) -> backbone_core::ServiceResult<Self> {
        self.name = dto.name;
        self.first_name = dto.first_name;
        self.last_name = dto.last_name;
        self.email = dto.email;
        self.company_name = dto.company_name;
        self.country_code = dto.country_code;
        self.phone = dto.phone;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to MailingContact here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
