//! Domain specifications
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Combinators (AND/OR/NOT) come from `backbone_core::Specification`.

pub use backbone_core::{Specification, AndSpecification, OrSpecification, NotSpecification};

pub mod mailing_ab_test_specification;
pub mod mailing_audience_specification;
pub mod mailing_contact_specification;
pub mod mailing_subscription_specification;
pub mod opt_out_reason_specification;
pub mod mailing_specification;
pub mod mailing_trace_specification;
pub mod mailing_filter_specification;

// <<< CUSTOM
// END CUSTOM
