//! Domain policies
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod mailing_ab_test_domain_policy;
pub mod mailing_audience_domain_policy;
pub mod mailing_contact_domain_policy;
pub mod mailing_subscription_domain_policy;
pub mod opt_out_reason_domain_policy;
pub mod mailing_domain_policy;
pub mod mailing_trace_domain_policy;
pub mod mailing_filter_domain_policy;

pub use mailing_ab_test_domain_policy::MailingAbTestDomainPolicy;
pub use mailing_audience_domain_policy::MailingAudienceDomainPolicy;
pub use mailing_contact_domain_policy::MailingContactDomainPolicy;
pub use mailing_subscription_domain_policy::MailingSubscriptionDomainPolicy;
pub use opt_out_reason_domain_policy::OptOutReasonDomainPolicy;
pub use mailing_domain_policy::MailingDomainPolicy;
pub use mailing_trace_domain_policy::MailingTraceDomainPolicy;
pub use mailing_filter_domain_policy::MailingFilterDomainPolicy;

// <<< CUSTOM
// END CUSTOM
