//! Application service for MailingAudience entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `mailing_audience_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateMailingAudienceDto, UpdateMailingAudienceDto};
use crate::domain::entity::MailingAudience;
use crate::infrastructure::persistence::MailingAudienceRepository;

/// Application service for MailingAudience entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `mailing_audience_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct MailingAudienceServiceCustom {
///     inner: Arc<MailingAudienceService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type MailingAudienceService = GenericCrudService<
    MailingAudience,
    CreateMailingAudienceDto,
    UpdateMailingAudienceDto,
    MailingAudienceRepository,
>;

// <<< CUSTOM
// END CUSTOM
