//! Application service for Mailing entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `mailing_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateMailingDto, UpdateMailingDto};
use crate::domain::entity::Mailing;
use crate::infrastructure::persistence::MailingRepository;

/// Application service for Mailing entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `mailing_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct MailingServiceCustom {
///     inner: Arc<MailingService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type MailingService = GenericCrudService<
    Mailing,
    CreateMailingDto,
    UpdateMailingDto,
    MailingRepository,
>;

// <<< CUSTOM
// END CUSTOM
