//! Application service for MailingSubscription entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `mailing_subscription_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateMailingSubscriptionDto, UpdateMailingSubscriptionDto};
use crate::domain::entity::MailingSubscription;
use crate::infrastructure::persistence::MailingSubscriptionRepository;

/// Application service for MailingSubscription entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `mailing_subscription_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct MailingSubscriptionServiceCustom {
///     inner: Arc<MailingSubscriptionService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type MailingSubscriptionService = GenericCrudService<
    MailingSubscription,
    CreateMailingSubscriptionDto,
    UpdateMailingSubscriptionDto,
    MailingSubscriptionRepository,
>;

// <<< CUSTOM
// END CUSTOM
