//! Application service for MailingFilter entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `mailing_filter_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateMailingFilterDto, UpdateMailingFilterDto};
use crate::domain::entity::MailingFilter;
use crate::infrastructure::persistence::MailingFilterRepository;

/// Application service for MailingFilter entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `mailing_filter_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct MailingFilterServiceCustom {
///     inner: Arc<MailingFilterService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type MailingFilterService = GenericCrudService<
    MailingFilter,
    CreateMailingFilterDto,
    UpdateMailingFilterDto,
    MailingFilterRepository,
>;

// <<< CUSTOM
// END CUSTOM
