//! Application service for MailingAbTest entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `mailing_ab_test_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateMailingAbTestDto, UpdateMailingAbTestDto};
use crate::domain::entity::MailingAbTest;
use crate::infrastructure::persistence::MailingAbTestRepository;

/// Application service for MailingAbTest entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `mailing_ab_test_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct MailingAbTestServiceCustom {
///     inner: Arc<MailingAbTestService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type MailingAbTestService = GenericCrudService<
    MailingAbTest,
    CreateMailingAbTestDto,
    UpdateMailingAbTestDto,
    MailingAbTestRepository,
>;

// <<< CUSTOM
// END CUSTOM
