//! Application service for MailingTrace entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `mailing_trace_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateMailingTraceDto, UpdateMailingTraceDto};
use crate::domain::entity::MailingTrace;
use crate::infrastructure::persistence::MailingTraceRepository;

/// Application service for MailingTrace entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `mailing_trace_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct MailingTraceServiceCustom {
///     inner: Arc<MailingTraceService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type MailingTraceService = GenericCrudService<
    MailingTrace,
    CreateMailingTraceDto,
    UpdateMailingTraceDto,
    MailingTraceRepository,
>;

// <<< CUSTOM
// END CUSTOM
