//! Application service for MailingContact entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `mailing_contact_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateMailingContactDto, UpdateMailingContactDto};
use crate::domain::entity::MailingContact;
use crate::infrastructure::persistence::MailingContactRepository;

/// Application service for MailingContact entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `mailing_contact_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct MailingContactServiceCustom {
///     inner: Arc<MailingContactService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type MailingContactService = GenericCrudService<
    MailingContact,
    CreateMailingContactDto,
    UpdateMailingContactDto,
    MailingContactRepository,
>;

// <<< CUSTOM
// END CUSTOM
