-- MailingAbTest Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the mailing.mailing_ab_tests table.
-- Customize this file to add your initial data.

-- INSERT INTO mailing.mailing_ab_tests (
--     id,
--     campaign_id,
--     winner_selection,
--     promote_at,
--     completed,
--     winner_mailing_id,
--     sampling_seed,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO mailing.mailing_ab_tests (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

