-- Mailing Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the mailing.mailings table.
-- Customize this file to add your initial data.

-- INSERT INTO mailing.mailings (
--     id,
--     subject,
--     preview,
--     body_html,
--     email_from,
--     reply_to,
--     keep_archives,
--     state,
--     schedule_type,
--     schedule_date,
--     sent_date,
--     mailing_type,
--     target_model,
--     mailing_domain,
--     use_exclusion_list,
--     campaign_id,
--     medium_id,
--     source_id,
--     user_id,
--     ab_testing_enabled,
--     ab_testing_pc,
--     ab_test_id,
--     kpi_mail_required,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO mailing.mailings (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

