-- MailingSubscription Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the mailing.mailing_subscriptions table.
-- Customize this file to add your initial data.

-- INSERT INTO mailing.mailing_subscriptions (
--     id,
--     contact_id,
--     mailing_audience_id,
--     opt_out,
--     opt_out_datetime,
--     opt_out_reason_id,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO mailing.mailing_subscriptions (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

