-- MailingTrace Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the mailing.mailing_traces table.
-- Customize this file to add your initial data.

-- INSERT INTO mailing.mailing_traces (
--     id,
--     trace_type,
--     is_test_trace,
--     mailing_id,
--     campaign_id,
--     recipient_model,
--     recipient_id,
--     recipient_email,
--     mail_id,
--     message_id,
--     trace_status,
--     failure_type,
--     failure_reason,
--     sent_datetime,
--     open_datetime,
--     reply_datetime,
--     links_click_datetime,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO mailing.mailing_traces (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

