-- Migration: Create mailing_ab_tests table
-- Generated by metaphor-schema

-- Create ab_winner_selection enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'ab_winner_selection') THEN
        CREATE TYPE ab_winner_selection AS ENUM ('manual', 'opened_ratio', 'clicks_ratio', 'replied_ratio');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS mailing;

CREATE TABLE IF NOT EXISTS mailing.mailing_ab_tests (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    campaign_id UUID NOT NULL,
    winner_selection ab_winner_selection NOT NULL DEFAULT 'opened_ratio',
    promote_at TIMESTAMPTZ,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    winner_mailing_id UUID,
    sampling_seed TEXT NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_mailing_ab_tests_campaign_id ON mailing.mailing_ab_tests (campaign_id) WHERE (metadata->>'deleted_at') IS NULL;

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_mailing_ab_tests_metadata_gin ON mailing.mailing_ab_tests USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_mailing_ab_tests_metadata_deleted_at ON mailing.mailing_ab_tests ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_mailing_ab_tests_metadata_created_at ON mailing.mailing_ab_tests ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_mailing_ab_tests_metadata_updated_at ON mailing.mailing_ab_tests ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION mailing.mailing_ab_tests_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS mailing_ab_tests_insert_audit ON mailing.mailing_ab_tests;
CREATE TRIGGER mailing_ab_tests_insert_audit BEFORE INSERT ON mailing.mailing_ab_tests
    FOR EACH ROW EXECUTE FUNCTION mailing.mailing_ab_tests_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS mailing_ab_tests_update_audit ON mailing.mailing_ab_tests;
CREATE TRIGGER mailing_ab_tests_update_audit BEFORE UPDATE ON mailing.mailing_ab_tests
    FOR EACH ROW EXECUTE FUNCTION mailing.mailing_ab_tests_audit_timestamp();
