-- Migration: Create mailing_subscriptions table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS mailing;

CREATE TABLE IF NOT EXISTS mailing.mailing_subscriptions (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    contact_id UUID NOT NULL,
    mailing_audience_id UUID NOT NULL,
    opt_out BOOLEAN NOT NULL DEFAULT FALSE,
    opt_out_datetime TIMESTAMPTZ,
    opt_out_reason_id UUID,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_mailing_subscriptions_contact_id_mailing_audience_id ON mailing.mailing_subscriptions (contact_id, mailing_audience_id) WHERE (metadata->>'deleted_at') IS NULL;

CREATE INDEX IF NOT EXISTS idx_mailing_subscriptions_mailing_audience_id_opt_out ON mailing.mailing_subscriptions (mailing_audience_id, opt_out);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_mailing_subscriptions_metadata_gin ON mailing.mailing_subscriptions USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_mailing_subscriptions_metadata_deleted_at ON mailing.mailing_subscriptions ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_mailing_subscriptions_metadata_created_at ON mailing.mailing_subscriptions ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_mailing_subscriptions_metadata_updated_at ON mailing.mailing_subscriptions ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION mailing.mailing_subscriptions_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS mailing_subscriptions_insert_audit ON mailing.mailing_subscriptions;
CREATE TRIGGER mailing_subscriptions_insert_audit BEFORE INSERT ON mailing.mailing_subscriptions
    FOR EACH ROW EXECUTE FUNCTION mailing.mailing_subscriptions_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS mailing_subscriptions_update_audit ON mailing.mailing_subscriptions;
CREATE TRIGGER mailing_subscriptions_update_audit BEFORE UPDATE ON mailing.mailing_subscriptions
    FOR EACH ROW EXECUTE FUNCTION mailing.mailing_subscriptions_audit_timestamp();
