-- Migration: Create mailings table
-- Generated by metaphor-schema

-- Create mailing_state enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'mailing_state') THEN
        CREATE TYPE mailing_state AS ENUM ('draft', 'in_queue', 'sending', 'done');
    END IF;
END
$$;

-- Create mailing_schedule_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'mailing_schedule_type') THEN
        CREATE TYPE mailing_schedule_type AS ENUM ('immediate', 'scheduled');
    END IF;
END
$$;

-- Create mailing_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'mailing_type') THEN
        CREATE TYPE mailing_type AS ENUM ('mail');
    END IF;
END
$$;

-- Create mailing_target_model enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'mailing_target_model') THEN
        CREATE TYPE mailing_target_model AS ENUM ('mailing_contact', 'party');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS mailing;

CREATE TABLE IF NOT EXISTS mailing.mailings (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    subject TEXT NOT NULL,
    preview TEXT,
    body_html TEXT NOT NULL,
    email_from TEXT NOT NULL,
    reply_to TEXT,
    keep_archives BOOLEAN NOT NULL DEFAULT TRUE,
    state mailing_state NOT NULL DEFAULT 'draft',
    schedule_type mailing_schedule_type NOT NULL DEFAULT 'immediate',
    schedule_date TIMESTAMPTZ,
    sent_date TIMESTAMPTZ,
    mailing_type mailing_type NOT NULL DEFAULT 'mail',
    target_model mailing_target_model NOT NULL DEFAULT 'mailing_contact',
    mailing_domain JSONB NOT NULL DEFAULT '{}'::jsonb,
    use_exclusion_list BOOLEAN NOT NULL DEFAULT TRUE,
    campaign_id UUID,
    medium_id UUID,
    source_id UUID,
    user_id UUID,
    ab_testing_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    ab_testing_pc INTEGER NOT NULL DEFAULT 10,
    ab_test_id UUID,
    kpi_mail_required BOOLEAN NOT NULL DEFAULT FALSE,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_mailings_state_schedule_date ON mailing.mailings (state, schedule_date);

CREATE INDEX IF NOT EXISTS idx_mailings_campaign_id ON mailing.mailings (campaign_id);

CREATE INDEX IF NOT EXISTS idx_mailings_ab_test_id ON mailing.mailings (ab_test_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_mailings_metadata_gin ON mailing.mailings USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_mailings_metadata_deleted_at ON mailing.mailings ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_mailings_metadata_created_at ON mailing.mailings ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_mailings_metadata_updated_at ON mailing.mailings ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION mailing.mailings_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS mailings_insert_audit ON mailing.mailings;
CREATE TRIGGER mailings_insert_audit BEFORE INSERT ON mailing.mailings
    FOR EACH ROW EXECUTE FUNCTION mailing.mailings_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS mailings_update_audit ON mailing.mailings;
CREATE TRIGGER mailings_update_audit BEFORE UPDATE ON mailing.mailings
    FOR EACH ROW EXECUTE FUNCTION mailing.mailings_audit_timestamp();
