-- Migration: Create mailing_traces table
-- Generated by metaphor-schema

-- Create trace_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'trace_type') THEN
        CREATE TYPE trace_type AS ENUM ('mail');
    END IF;
END
$$;

-- Create trace_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'trace_status') THEN
        CREATE TYPE trace_status AS ENUM ('outgoing', 'process', 'pending', 'sent', 'open', 'reply', 'bounce', 'error', 'cancel');
    END IF;
END
$$;

-- Create trace_failure_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'trace_failure_type') THEN
        CREATE TYPE trace_failure_type AS ENUM ('unknown', 'mail_bounce', 'mail_spam', 'mail_email_invalid', 'mail_email_missing', 'mail_from_invalid', 'mail_from_missing', 'mail_smtp', 'mail_bl', 'mail_dup', 'mail_optout');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS mailing;

CREATE TABLE IF NOT EXISTS mailing.mailing_traces (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    trace_type trace_type NOT NULL DEFAULT 'mail',
    is_test_trace BOOLEAN NOT NULL DEFAULT FALSE,
    mailing_id UUID NOT NULL,
    campaign_id UUID,
    recipient_model TEXT NOT NULL,
    recipient_id UUID NOT NULL,
    recipient_email TEXT NOT NULL,
    mail_id UUID,
    message_id TEXT,
    trace_status trace_status NOT NULL DEFAULT 'outgoing',
    failure_type trace_failure_type,
    failure_reason TEXT,
    sent_datetime TIMESTAMPTZ,
    open_datetime TIMESTAMPTZ,
    reply_datetime TIMESTAMPTZ,
    links_click_datetime TIMESTAMPTZ,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_mailing_traces_mailing_id_recipient_id ON mailing.mailing_traces (mailing_id, recipient_id) WHERE (metadata->>'deleted_at') IS NULL AND trace_status <> 'cancel';

CREATE INDEX IF NOT EXISTS idx_mailing_traces_campaign_id_recipient_id ON mailing.mailing_traces (campaign_id, recipient_id);

CREATE INDEX IF NOT EXISTS idx_mailing_traces_mailing_id_trace_status ON mailing.mailing_traces (mailing_id, trace_status);

CREATE INDEX IF NOT EXISTS idx_mailing_traces_recipient_email_failure_type ON mailing.mailing_traces (recipient_email, failure_type);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_mailing_traces_metadata_gin ON mailing.mailing_traces USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_mailing_traces_metadata_deleted_at ON mailing.mailing_traces ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_mailing_traces_metadata_created_at ON mailing.mailing_traces ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_mailing_traces_metadata_updated_at ON mailing.mailing_traces ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION mailing.mailing_traces_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS mailing_traces_insert_audit ON mailing.mailing_traces;
CREATE TRIGGER mailing_traces_insert_audit BEFORE INSERT ON mailing.mailing_traces
    FOR EACH ROW EXECUTE FUNCTION mailing.mailing_traces_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS mailing_traces_update_audit ON mailing.mailing_traces;
CREATE TRIGGER mailing_traces_update_audit BEFORE UPDATE ON mailing.mailing_traces
    FOR EACH ROW EXECUTE FUNCTION mailing.mailing_traces_audit_timestamp();
