-- Migration: Create mailing_opt_out_reasons table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS mailing;

CREATE TABLE IF NOT EXISTS mailing.mailing_opt_out_reasons (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    sequence INTEGER NOT NULL DEFAULT 10,
    is_feedback BOOLEAN NOT NULL DEFAULT FALSE,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_mailing_opt_out_reasons_metadata_gin ON mailing.mailing_opt_out_reasons USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_mailing_opt_out_reasons_metadata_deleted_at ON mailing.mailing_opt_out_reasons ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_mailing_opt_out_reasons_metadata_created_at ON mailing.mailing_opt_out_reasons ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_mailing_opt_out_reasons_metadata_updated_at ON mailing.mailing_opt_out_reasons ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION mailing.mailing_opt_out_reasons_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS mailing_opt_out_reasons_insert_audit ON mailing.mailing_opt_out_reasons;
CREATE TRIGGER mailing_opt_out_reasons_insert_audit BEFORE INSERT ON mailing.mailing_opt_out_reasons
    FOR EACH ROW EXECUTE FUNCTION mailing.mailing_opt_out_reasons_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS mailing_opt_out_reasons_update_audit ON mailing.mailing_opt_out_reasons;
CREATE TRIGGER mailing_opt_out_reasons_update_audit BEFORE UPDATE ON mailing.mailing_opt_out_reasons
    FOR EACH ROW EXECUTE FUNCTION mailing.mailing_opt_out_reasons_audit_timestamp();
