-- Migration: Create mailing_contacts table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS mailing;

CREATE TABLE IF NOT EXISTS mailing.mailing_contacts (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    name TEXT,
    first_name TEXT,
    last_name TEXT,
    email TEXT NOT NULL,
    company_name TEXT,
    country_code TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_mailing_contacts_email ON mailing.mailing_contacts (email) WHERE (metadata->>'deleted_at') IS NULL;

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_mailing_contacts_metadata_gin ON mailing.mailing_contacts USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_mailing_contacts_metadata_deleted_at ON mailing.mailing_contacts ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_mailing_contacts_metadata_created_at ON mailing.mailing_contacts ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_mailing_contacts_metadata_updated_at ON mailing.mailing_contacts ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION mailing.mailing_contacts_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS mailing_contacts_insert_audit ON mailing.mailing_contacts;
CREATE TRIGGER mailing_contacts_insert_audit BEFORE INSERT ON mailing.mailing_contacts
    FOR EACH ROW EXECUTE FUNCTION mailing.mailing_contacts_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS mailing_contacts_update_audit ON mailing.mailing_contacts;
CREATE TRIGGER mailing_contacts_update_audit BEFORE UPDATE ON mailing.mailing_contacts
    FOR EACH ROW EXECUTE FUNCTION mailing.mailing_contacts_audit_timestamp();
