-- Enum types for mailing module
-- Generated by metaphor-schema

-- Create ab_winner_selection enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'ab_winner_selection') THEN
        CREATE TYPE ab_winner_selection AS ENUM ('manual', 'opened_ratio', 'clicks_ratio', 'replied_ratio');
    END IF;
END
$$;

-- Create mailing_state enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'mailing_state') THEN
        CREATE TYPE mailing_state AS ENUM ('draft', 'in_queue', 'sending', 'done');
    END IF;
END
$$;

-- Create mailing_schedule_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'mailing_schedule_type') THEN
        CREATE TYPE mailing_schedule_type AS ENUM ('immediate', 'scheduled');
    END IF;
END
$$;

-- Create mailing_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'mailing_type') THEN
        CREATE TYPE mailing_type AS ENUM ('mail');
    END IF;
END
$$;

-- Create mailing_target_model enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'mailing_target_model') THEN
        CREATE TYPE mailing_target_model AS ENUM ('mailing_contact', 'party');
    END IF;
END
$$;

-- Create trace_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'trace_type') THEN
        CREATE TYPE trace_type AS ENUM ('mail');
    END IF;
END
$$;

-- Create trace_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'trace_status') THEN
        CREATE TYPE trace_status AS ENUM ('outgoing', 'process', 'pending', 'sent', 'open', 'reply', 'bounce', 'error', 'cancel');
    END IF;
END
$$;

-- Create trace_failure_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'trace_failure_type') THEN
        CREATE TYPE trace_failure_type AS ENUM ('unknown', 'mail_bounce', 'mail_spam', 'mail_email_invalid', 'mail_email_missing', 'mail_from_invalid', 'mail_from_missing', 'mail_smtp', 'mail_bl', 'mail_dup', 'mail_optout');
    END IF;
END
$$;

