-- Audit Triggers Migration for mailing module
-- Generated by metaphor-schema
--
-- This migration adds automatic timestamp management triggers
-- to all tables with audit metadata fields.
--
-- Triggers automatically set:
--   - metadata->'created_at' on INSERT
--   - metadata->'updated_at' on INSERT and UPDATE

-- ==============================================================================
-- Table: MailingAbTest (mailing.mailing_ab_tests)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION mailing.mailing_ab_tests_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS mailing_ab_tests_insert_audit ON mailing.mailing_ab_tests;
CREATE TRIGGER mailing_ab_tests_insert_audit BEFORE INSERT ON mailing.mailing_ab_tests
    FOR EACH ROW EXECUTE FUNCTION mailing.mailing_ab_tests_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS mailing_ab_tests_update_audit ON mailing.mailing_ab_tests;
CREATE TRIGGER mailing_ab_tests_update_audit BEFORE UPDATE ON mailing.mailing_ab_tests
    FOR EACH ROW EXECUTE FUNCTION mailing.mailing_ab_tests_audit_timestamp();

-- ==============================================================================
-- Table: MailingAudience (mailing.mailing_audiences)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION mailing.mailing_audiences_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS mailing_audiences_insert_audit ON mailing.mailing_audiences;
CREATE TRIGGER mailing_audiences_insert_audit BEFORE INSERT ON mailing.mailing_audiences
    FOR EACH ROW EXECUTE FUNCTION mailing.mailing_audiences_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS mailing_audiences_update_audit ON mailing.mailing_audiences;
CREATE TRIGGER mailing_audiences_update_audit BEFORE UPDATE ON mailing.mailing_audiences
    FOR EACH ROW EXECUTE FUNCTION mailing.mailing_audiences_audit_timestamp();

-- ==============================================================================
-- Table: MailingContact (mailing.mailing_contacts)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION mailing.mailing_contacts_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS mailing_contacts_insert_audit ON mailing.mailing_contacts;
CREATE TRIGGER mailing_contacts_insert_audit BEFORE INSERT ON mailing.mailing_contacts
    FOR EACH ROW EXECUTE FUNCTION mailing.mailing_contacts_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS mailing_contacts_update_audit ON mailing.mailing_contacts;
CREATE TRIGGER mailing_contacts_update_audit BEFORE UPDATE ON mailing.mailing_contacts
    FOR EACH ROW EXECUTE FUNCTION mailing.mailing_contacts_audit_timestamp();

-- ==============================================================================
-- Table: MailingSubscription (mailing.mailing_subscriptions)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION mailing.mailing_subscriptions_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS mailing_subscriptions_insert_audit ON mailing.mailing_subscriptions;
CREATE TRIGGER mailing_subscriptions_insert_audit BEFORE INSERT ON mailing.mailing_subscriptions
    FOR EACH ROW EXECUTE FUNCTION mailing.mailing_subscriptions_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS mailing_subscriptions_update_audit ON mailing.mailing_subscriptions;
CREATE TRIGGER mailing_subscriptions_update_audit BEFORE UPDATE ON mailing.mailing_subscriptions
    FOR EACH ROW EXECUTE FUNCTION mailing.mailing_subscriptions_audit_timestamp();

-- ==============================================================================
-- Table: OptOutReason (mailing.mailing_opt_out_reasons)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION mailing.mailing_opt_out_reasons_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS mailing_opt_out_reasons_insert_audit ON mailing.mailing_opt_out_reasons;
CREATE TRIGGER mailing_opt_out_reasons_insert_audit BEFORE INSERT ON mailing.mailing_opt_out_reasons
    FOR EACH ROW EXECUTE FUNCTION mailing.mailing_opt_out_reasons_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS mailing_opt_out_reasons_update_audit ON mailing.mailing_opt_out_reasons;
CREATE TRIGGER mailing_opt_out_reasons_update_audit BEFORE UPDATE ON mailing.mailing_opt_out_reasons
    FOR EACH ROW EXECUTE FUNCTION mailing.mailing_opt_out_reasons_audit_timestamp();

-- ==============================================================================
-- Table: Mailing (mailing.mailings)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION mailing.mailings_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS mailings_insert_audit ON mailing.mailings;
CREATE TRIGGER mailings_insert_audit BEFORE INSERT ON mailing.mailings
    FOR EACH ROW EXECUTE FUNCTION mailing.mailings_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS mailings_update_audit ON mailing.mailings;
CREATE TRIGGER mailings_update_audit BEFORE UPDATE ON mailing.mailings
    FOR EACH ROW EXECUTE FUNCTION mailing.mailings_audit_timestamp();

-- ==============================================================================
-- Table: MailingTrace (mailing.mailing_traces)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION mailing.mailing_traces_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS mailing_traces_insert_audit ON mailing.mailing_traces;
CREATE TRIGGER mailing_traces_insert_audit BEFORE INSERT ON mailing.mailing_traces
    FOR EACH ROW EXECUTE FUNCTION mailing.mailing_traces_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS mailing_traces_update_audit ON mailing.mailing_traces;
CREATE TRIGGER mailing_traces_update_audit BEFORE UPDATE ON mailing.mailing_traces
    FOR EACH ROW EXECUTE FUNCTION mailing.mailing_traces_audit_timestamp();

-- ==============================================================================
-- Table: MailingFilter (mailing.mailing_filters)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION mailing.mailing_filters_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS mailing_filters_insert_audit ON mailing.mailing_filters;
CREATE TRIGGER mailing_filters_insert_audit BEFORE INSERT ON mailing.mailing_filters
    FOR EACH ROW EXECUTE FUNCTION mailing.mailing_filters_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS mailing_filters_update_audit ON mailing.mailing_filters;
CREATE TRIGGER mailing_filters_update_audit BEFORE UPDATE ON mailing.mailing_filters
    FOR EACH ROW EXECUTE FUNCTION mailing.mailing_filters_audit_timestamp();

