-- Migration: Create mailing_filters table
-- Generated by metaphor-schema

-- Create mailing_target_model enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'mailing_target_model') THEN
        CREATE TYPE mailing_target_model AS ENUM ('mailing_contact', 'party');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS mailing;

CREATE TABLE IF NOT EXISTS mailing.mailing_filters (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    target_model mailing_target_model NOT NULL DEFAULT 'mailing_contact',
    domain JSONB NOT NULL DEFAULT '{}'::jsonb,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_mailing_filters_metadata_gin ON mailing.mailing_filters USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_mailing_filters_metadata_deleted_at ON mailing.mailing_filters ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_mailing_filters_metadata_created_at ON mailing.mailing_filters ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_mailing_filters_metadata_updated_at ON mailing.mailing_filters ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION mailing.mailing_filters_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS mailing_filters_insert_audit ON mailing.mailing_filters;
CREATE TRIGGER mailing_filters_insert_audit BEFORE INSERT ON mailing.mailing_filters
    FOR EACH ROW EXECUTE FUNCTION mailing.mailing_filters_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS mailing_filters_update_audit ON mailing.mailing_filters;
CREATE TRIGGER mailing_filters_update_audit BEFORE UPDATE ON mailing.mailing_filters
    FOR EACH ROW EXECUTE FUNCTION mailing.mailing_filters_audit_timestamp();
