//! Domain events for MailingAbTest entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::MailingAbTest;

/// Domain events for MailingAbTest — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<MailingAbTest>)` variant.
pub type MailingAbTestEvent = CrudEvent<MailingAbTest>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for MailingAbTest events.
pub type MailingAbTestEventPublisher = Arc<dyn CrudEventPublisher<MailingAbTest> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopMailingAbTestEventPublisher = NoOpCrudEventPublisher<MailingAbTest>;
