//! Event handler trait for MailingContact events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::MailingContactEvent;

/// Event handler for MailingContact events.
/// Implement this trait to react to MailingContact lifecycle events.
pub trait MailingContactEventHandler: EventHandler<MailingContactEvent> {}
