//! Event handler trait for MailingAbTest events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::MailingAbTestEvent;

/// Event handler for MailingAbTest events.
/// Implement this trait to react to MailingAbTest lifecycle events.
pub trait MailingAbTestEventHandler: EventHandler<MailingAbTestEvent> {}
