//! Event handler trait for MailingSubscription events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::MailingSubscriptionEvent;

/// Event handler for MailingSubscription events.
/// Implement this trait to react to MailingSubscription lifecycle events.
pub trait MailingSubscriptionEventHandler: EventHandler<MailingSubscriptionEvent> {}
