//! Domain events for MailingTrace entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::MailingTrace;

/// Domain events for MailingTrace — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<MailingTrace>)` variant.
pub type MailingTraceEvent = CrudEvent<MailingTrace>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for MailingTrace events.
pub type MailingTraceEventPublisher = Arc<dyn CrudEventPublisher<MailingTrace> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopMailingTraceEventPublisher = NoOpCrudEventPublisher<MailingTrace>;
