//! Event handler trait for Mailing events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::MailingEvent;

/// Event handler for Mailing events.
/// Implement this trait to react to Mailing lifecycle events.
pub trait MailingEventHandler: EventHandler<MailingEvent> {}
