//! Domain events for MailingContact entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::MailingContact;

/// Domain events for MailingContact — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<MailingContact>)` variant.
pub type MailingContactEvent = CrudEvent<MailingContact>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for MailingContact events.
pub type MailingContactEventPublisher = Arc<dyn CrudEventPublisher<MailingContact> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopMailingContactEventPublisher = NoOpCrudEventPublisher<MailingContact>;
