//! Event handler trait for MailingTrace events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::MailingTraceEvent;

/// Event handler for MailingTrace events.
/// Implement this trait to react to MailingTrace lifecycle events.
pub trait MailingTraceEventHandler: EventHandler<MailingTraceEvent> {}
