//! Domain events for Mailing entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Mailing;

/// Domain events for Mailing — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Mailing>)` variant.
pub type MailingEvent = CrudEvent<Mailing>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Mailing events.
pub type MailingEventPublisher = Arc<dyn CrudEventPublisher<Mailing> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopMailingEventPublisher = NoOpCrudEventPublisher<Mailing>;
