//! Domain events for MailingFilter entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::MailingFilter;

/// Domain events for MailingFilter — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<MailingFilter>)` variant.
pub type MailingFilterEvent = CrudEvent<MailingFilter>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for MailingFilter events.
pub type MailingFilterEventPublisher = Arc<dyn CrudEventPublisher<MailingFilter> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopMailingFilterEventPublisher = NoOpCrudEventPublisher<MailingFilter>;
