//! Event handler trait for MailingAudience events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::MailingAudienceEvent;

/// Event handler for MailingAudience events.
/// Implement this trait to react to MailingAudience lifecycle events.
pub trait MailingAudienceEventHandler: EventHandler<MailingAudienceEvent> {}
