//! Domain events for MailingSubscription entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::MailingSubscription;

/// Domain events for MailingSubscription — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<MailingSubscription>)` variant.
pub type MailingSubscriptionEvent = CrudEvent<MailingSubscription>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for MailingSubscription events.
pub type MailingSubscriptionEventPublisher = Arc<dyn CrudEventPublisher<MailingSubscription> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopMailingSubscriptionEventPublisher = NoOpCrudEventPublisher<MailingSubscription>;
