//! Event handler trait for MailingFilter events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::MailingFilterEvent;

/// Event handler for MailingFilter events.
/// Implement this trait to react to MailingFilter lifecycle events.
pub trait MailingFilterEventHandler: EventHandler<MailingFilterEvent> {}
