//! Domain events
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod mailing_ab_test_events;
pub mod mailing_ab_test_event_handlers;
pub mod mailing_audience_events;
pub mod mailing_audience_event_handlers;
pub mod mailing_contact_events;
pub mod mailing_contact_event_handlers;
pub mod mailing_subscription_events;
pub mod mailing_subscription_event_handlers;
pub mod opt_out_reason_events;
pub mod opt_out_reason_event_handlers;
pub mod mailing_events;
pub mod mailing_event_handlers;
pub mod mailing_trace_events;
pub mod mailing_trace_event_handlers;
pub mod mailing_filter_events;
pub mod mailing_filter_event_handlers;

pub use mailing_ab_test_events::{MailingAbTestEvent, MailingAbTestEventPublisher, NoopMailingAbTestEventPublisher};
pub use mailing_ab_test_event_handlers::MailingAbTestEventHandler;
pub use mailing_audience_events::{MailingAudienceEvent, MailingAudienceEventPublisher, NoopMailingAudienceEventPublisher};
pub use mailing_audience_event_handlers::MailingAudienceEventHandler;
pub use mailing_contact_events::{MailingContactEvent, MailingContactEventPublisher, NoopMailingContactEventPublisher};
pub use mailing_contact_event_handlers::MailingContactEventHandler;
pub use mailing_subscription_events::{MailingSubscriptionEvent, MailingSubscriptionEventPublisher, NoopMailingSubscriptionEventPublisher};
pub use mailing_subscription_event_handlers::MailingSubscriptionEventHandler;
pub use opt_out_reason_events::{OptOutReasonEvent, OptOutReasonEventPublisher, NoopOptOutReasonEventPublisher};
pub use opt_out_reason_event_handlers::OptOutReasonEventHandler;
pub use mailing_events::{MailingEvent, MailingEventPublisher, NoopMailingEventPublisher};
pub use mailing_event_handlers::MailingEventHandler;
pub use mailing_trace_events::{MailingTraceEvent, MailingTraceEventPublisher, NoopMailingTraceEventPublisher};
pub use mailing_trace_event_handlers::MailingTraceEventHandler;
pub use mailing_filter_events::{MailingFilterEvent, MailingFilterEventPublisher, NoopMailingFilterEventPublisher};
pub use mailing_filter_event_handlers::MailingFilterEventHandler;

// <<< CUSTOM
// END CUSTOM
