//! Domain events for OptOutReason entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::OptOutReason;

/// Domain events for OptOutReason — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<OptOutReason>)` variant.
pub type OptOutReasonEvent = CrudEvent<OptOutReason>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for OptOutReason events.
pub type OptOutReasonEventPublisher = Arc<dyn CrudEventPublisher<OptOutReason> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopOptOutReasonEventPublisher = NoOpCrudEventPublisher<OptOutReason>;
