//! Event handler trait for OptOutReason events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::OptOutReasonEvent;

/// Event handler for OptOutReason events.
/// Implement this trait to react to OptOutReason lifecycle events.
pub trait OptOutReasonEventHandler: EventHandler<OptOutReasonEvent> {}
