//! MailingAudience seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial MailingAudience data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// MAILINGAUDIENCE SEEDER
// ============================================================================

/// Seeder for mailing_audience
pub struct SeedMailingAudienceSeeder;

impl SeedMailingAudienceSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedMailingAudienceSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedMailingAudienceSeeder {
    fn name(&self) -> &'static str {
        "SeedMailingAudienceSeeder"
    }

    fn order(&self) -> i32 {
        2
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if mailing.mailing_audiences table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM mailing.mailing_audiences")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/mailing_audience_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM mailing.mailing_audiences")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>
