//! MailingContact seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial MailingContact data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// MAILINGCONTACT SEEDER
// ============================================================================

/// Seeder for mailing_contact
pub struct SeedMailingContactSeeder;

impl SeedMailingContactSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedMailingContactSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedMailingContactSeeder {
    fn name(&self) -> &'static str {
        "SeedMailingContactSeeder"
    }

    fn order(&self) -> i32 {
        3
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if mailing.mailing_contacts table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM mailing.mailing_contacts")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/mailing_contact_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM mailing.mailing_contacts")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>
