//! MailingSubscription seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial MailingSubscription data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// MAILINGSUBSCRIPTION SEEDER
// ============================================================================

/// Seeder for mailing_subscription
pub struct SeedMailingSubscriptionSeeder;

impl SeedMailingSubscriptionSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedMailingSubscriptionSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedMailingSubscriptionSeeder {
    fn name(&self) -> &'static str {
        "SeedMailingSubscriptionSeeder"
    }

    fn order(&self) -> i32 {
        4
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if mailing.mailing_subscriptions table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM mailing.mailing_subscriptions")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/mailing_subscription_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM mailing.mailing_subscriptions")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>
