//! MailingTrace seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial MailingTrace data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// MAILINGTRACE SEEDER
// ============================================================================

/// Seeder for mailing_trace
pub struct SeedMailingTraceSeeder;

impl SeedMailingTraceSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedMailingTraceSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedMailingTraceSeeder {
    fn name(&self) -> &'static str {
        "SeedMailingTraceSeeder"
    }

    fn order(&self) -> i32 {
        7
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if mailing.mailing_traces table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM mailing.mailing_traces")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/mailing_trace_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM mailing.mailing_traces")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>
