//! Repository trait for MailingAbTest aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the MailingAbTest aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{MailingAbTest, AbWinnerSelection};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct MailingAbTestPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl MailingAbTestPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct MailingAbTestPaginatedResult {
    pub data: Vec<MailingAbTest>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct MailingAbTestFilter {
    pub campaign_id: Option<Uuid>,
    pub winner_selection: Option<AbWinnerSelection>,
    pub winner_selection_sms: Option<AbWinnerSelection>,
    pub completed: Option<bool>,
    pub winner_mailing_id: Option<Uuid>,
    pub sampling_seed: Option<String>,
}

impl MailingAbTestFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.campaign_id.is_some() || self.winner_selection.is_some() || self.winner_selection_sms.is_some() || self.completed.is_some() || self.winner_mailing_id.is_some() || self.sampling_seed.is_some()
    }
}

/// Repository trait for MailingAbTest aggregate
///
/// This trait defines the persistence contract for MailingAbTest entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait MailingAbTestRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new mailing_ab_test entity
    async fn save(&self, entity: &MailingAbTest) -> Result<MailingAbTest>;

    /// Find mailing_ab_test by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<MailingAbTest>>;

    /// Find all mailing_ab_test entities
    async fn find_all(&self) -> Result<Vec<MailingAbTest>>;

    /// Update mailing_ab_test by ID
    async fn update(&self, id: &str, entity: &MailingAbTest) -> Result<Option<MailingAbTest>>;

    /// Delete mailing_ab_test by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List mailing_ab_test with pagination
    async fn list(&self, params: MailingAbTestPaginationParams) -> Result<MailingAbTestPaginatedResult>;

    /// List mailing_ab_test with pagination and filters
    async fn list_with_filters(&self, params: MailingAbTestPaginationParams, filters: MailingAbTestFilter) -> Result<MailingAbTestPaginatedResult>;

    /// Count all mailing_ab_test entities
    async fn count(&self) -> Result<u64>;

    /// Count mailing_ab_test entities matching filters
    async fn count_with_filters(&self, filters: MailingAbTestFilter) -> Result<u64>;

    /// Check if mailing_ab_test exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete mailing_ab_test by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted mailing_ab_test by ID
    async fn restore(&self, id: &str) -> Result<Option<MailingAbTest>>;

    /// List soft-deleted mailing_ab_test entities
    async fn list_deleted(&self, params: MailingAbTestPaginationParams) -> Result<MailingAbTestPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save mailing_ab_test entities
    async fn bulk_save(&self, entities: &[MailingAbTest]) -> Result<Vec<MailingAbTest>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
