//! Repository trait for MailingTrace aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the MailingTrace aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{MailingTrace, TraceFailureType, TraceStatus, TraceType};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct MailingTracePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl MailingTracePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct MailingTracePaginatedResult {
    pub data: Vec<MailingTrace>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct MailingTraceFilter {
    pub trace_type: Option<TraceType>,
    pub is_test_trace: Option<bool>,
    pub mailing_id: Option<Uuid>,
    pub campaign_id: Option<Uuid>,
    pub recipient_model: Option<String>,
    pub recipient_id: Option<Uuid>,
    pub recipient_email: Option<String>,
    pub mail_id: Option<Uuid>,
    pub message_id: Option<String>,
    pub trace_status: Option<TraceStatus>,
    pub failure_type: Option<TraceFailureType>,
    pub failure_reason: Option<String>,
}

impl MailingTraceFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.trace_type.is_some() || self.is_test_trace.is_some() || self.mailing_id.is_some() || self.campaign_id.is_some() || self.recipient_model.is_some() || self.recipient_id.is_some() || self.recipient_email.is_some() || self.mail_id.is_some() || self.message_id.is_some() || self.trace_status.is_some() || self.failure_type.is_some() || self.failure_reason.is_some()
    }
}

/// Repository trait for MailingTrace aggregate
///
/// This trait defines the persistence contract for MailingTrace entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait MailingTraceRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new mailing_trace entity
    async fn save(&self, entity: &MailingTrace) -> Result<MailingTrace>;

    /// Find mailing_trace by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<MailingTrace>>;

    /// Find all mailing_trace entities
    async fn find_all(&self) -> Result<Vec<MailingTrace>>;

    /// Update mailing_trace by ID
    async fn update(&self, id: &str, entity: &MailingTrace) -> Result<Option<MailingTrace>>;

    /// Delete mailing_trace by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List mailing_trace with pagination
    async fn list(&self, params: MailingTracePaginationParams) -> Result<MailingTracePaginatedResult>;

    /// List mailing_trace with pagination and filters
    async fn list_with_filters(&self, params: MailingTracePaginationParams, filters: MailingTraceFilter) -> Result<MailingTracePaginatedResult>;

    /// Count all mailing_trace entities
    async fn count(&self) -> Result<u64>;

    /// Count mailing_trace entities matching filters
    async fn count_with_filters(&self, filters: MailingTraceFilter) -> Result<u64>;

    /// Check if mailing_trace exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete mailing_trace by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted mailing_trace by ID
    async fn restore(&self, id: &str) -> Result<Option<MailingTrace>>;

    /// List soft-deleted mailing_trace entities
    async fn list_deleted(&self, params: MailingTracePaginationParams) -> Result<MailingTracePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save mailing_trace entities
    async fn bulk_save(&self, entities: &[MailingTrace]) -> Result<Vec<MailingTrace>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
