//! Repository trait for MailingSubscription aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the MailingSubscription aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::MailingSubscription;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct MailingSubscriptionPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl MailingSubscriptionPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct MailingSubscriptionPaginatedResult {
    pub data: Vec<MailingSubscription>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct MailingSubscriptionFilter {
    pub contact_id: Option<Uuid>,
    pub mailing_audience_id: Option<Uuid>,
    pub opt_out: Option<bool>,
    pub opt_out_reason_id: Option<Uuid>,
}

impl MailingSubscriptionFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.contact_id.is_some() || self.mailing_audience_id.is_some() || self.opt_out.is_some() || self.opt_out_reason_id.is_some()
    }
}

/// Repository trait for MailingSubscription aggregate
///
/// This trait defines the persistence contract for MailingSubscription entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait MailingSubscriptionRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new mailing_subscription entity
    async fn save(&self, entity: &MailingSubscription) -> Result<MailingSubscription>;

    /// Find mailing_subscription by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<MailingSubscription>>;

    /// Find all mailing_subscription entities
    async fn find_all(&self) -> Result<Vec<MailingSubscription>>;

    /// Update mailing_subscription by ID
    async fn update(&self, id: &str, entity: &MailingSubscription) -> Result<Option<MailingSubscription>>;

    /// Delete mailing_subscription by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List mailing_subscription with pagination
    async fn list(&self, params: MailingSubscriptionPaginationParams) -> Result<MailingSubscriptionPaginatedResult>;

    /// List mailing_subscription with pagination and filters
    async fn list_with_filters(&self, params: MailingSubscriptionPaginationParams, filters: MailingSubscriptionFilter) -> Result<MailingSubscriptionPaginatedResult>;

    /// Count all mailing_subscription entities
    async fn count(&self) -> Result<u64>;

    /// Count mailing_subscription entities matching filters
    async fn count_with_filters(&self, filters: MailingSubscriptionFilter) -> Result<u64>;

    /// Check if mailing_subscription exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete mailing_subscription by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted mailing_subscription by ID
    async fn restore(&self, id: &str) -> Result<Option<MailingSubscription>>;

    /// List soft-deleted mailing_subscription entities
    async fn list_deleted(&self, params: MailingSubscriptionPaginationParams) -> Result<MailingSubscriptionPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save mailing_subscription entities
    async fn bulk_save(&self, entities: &[MailingSubscription]) -> Result<Vec<MailingSubscription>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
