//! Repository trait for MailingContact aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the MailingContact aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;

use crate::domain::entity::MailingContact;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct MailingContactPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl MailingContactPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct MailingContactPaginatedResult {
    pub data: Vec<MailingContact>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct MailingContactFilter {
    pub name: Option<String>,
    pub first_name: Option<String>,
    pub last_name: Option<String>,
    pub email: Option<String>,
    pub company_name: Option<String>,
    pub country_code: Option<String>,
}

impl MailingContactFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.name.is_some() || self.first_name.is_some() || self.last_name.is_some() || self.email.is_some() || self.company_name.is_some() || self.country_code.is_some()
    }
}

/// Repository trait for MailingContact aggregate
///
/// This trait defines the persistence contract for MailingContact entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait MailingContactRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new mailing_contact entity
    async fn save(&self, entity: &MailingContact) -> Result<MailingContact>;

    /// Find mailing_contact by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<MailingContact>>;

    /// Find all mailing_contact entities
    async fn find_all(&self) -> Result<Vec<MailingContact>>;

    /// Update mailing_contact by ID
    async fn update(&self, id: &str, entity: &MailingContact) -> Result<Option<MailingContact>>;

    /// Delete mailing_contact by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List mailing_contact with pagination
    async fn list(&self, params: MailingContactPaginationParams) -> Result<MailingContactPaginatedResult>;

    /// List mailing_contact with pagination and filters
    async fn list_with_filters(&self, params: MailingContactPaginationParams, filters: MailingContactFilter) -> Result<MailingContactPaginatedResult>;

    /// Count all mailing_contact entities
    async fn count(&self) -> Result<u64>;

    /// Count mailing_contact entities matching filters
    async fn count_with_filters(&self, filters: MailingContactFilter) -> Result<u64>;

    /// Check if mailing_contact exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete mailing_contact by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted mailing_contact by ID
    async fn restore(&self, id: &str) -> Result<Option<MailingContact>>;

    /// List soft-deleted mailing_contact entities
    async fn list_deleted(&self, params: MailingContactPaginationParams) -> Result<MailingContactPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save mailing_contact entities
    async fn bulk_save(&self, entities: &[MailingContact]) -> Result<Vec<MailingContact>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
