//! Repository trait for Mailing aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Mailing aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{Mailing, MailingScheduleType, MailingState, MailingTargetModel, MailingType};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct MailingPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl MailingPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct MailingPaginatedResult {
    pub data: Vec<Mailing>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct MailingFilter {
    pub subject: Option<String>,
    pub preview: Option<String>,
    pub body_html: Option<String>,
    pub email_from: Option<String>,
    pub reply_to: Option<String>,
    pub keep_archives: Option<bool>,
    pub state: Option<MailingState>,
    pub schedule_type: Option<MailingScheduleType>,
    pub mailing_type: Option<MailingType>,
    pub target_model: Option<MailingTargetModel>,
    pub use_exclusion_list: Option<bool>,
    pub campaign_id: Option<Uuid>,
    pub medium_id: Option<Uuid>,
    pub source_id: Option<Uuid>,
    pub user_id: Option<Uuid>,
    pub ab_testing_enabled: Option<bool>,
    pub ab_test_id: Option<Uuid>,
    pub kpi_mail_required: Option<bool>,
}

impl MailingFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.subject.is_some() || self.preview.is_some() || self.body_html.is_some() || self.email_from.is_some() || self.reply_to.is_some() || self.keep_archives.is_some() || self.state.is_some() || self.schedule_type.is_some() || self.mailing_type.is_some() || self.target_model.is_some() || self.use_exclusion_list.is_some() || self.campaign_id.is_some() || self.medium_id.is_some() || self.source_id.is_some() || self.user_id.is_some() || self.ab_testing_enabled.is_some() || self.ab_test_id.is_some() || self.kpi_mail_required.is_some()
    }
}

/// Repository trait for Mailing aggregate
///
/// This trait defines the persistence contract for Mailing entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait MailingRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new mailing entity
    async fn save(&self, entity: &Mailing) -> Result<Mailing>;

    /// Find mailing by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Mailing>>;

    /// Find all mailing entities
    async fn find_all(&self) -> Result<Vec<Mailing>>;

    /// Update mailing by ID
    async fn update(&self, id: &str, entity: &Mailing) -> Result<Option<Mailing>>;

    /// Delete mailing by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List mailing with pagination
    async fn list(&self, params: MailingPaginationParams) -> Result<MailingPaginatedResult>;

    /// List mailing with pagination and filters
    async fn list_with_filters(&self, params: MailingPaginationParams, filters: MailingFilter) -> Result<MailingPaginatedResult>;

    /// Count all mailing entities
    async fn count(&self) -> Result<u64>;

    /// Count mailing entities matching filters
    async fn count_with_filters(&self, filters: MailingFilter) -> Result<u64>;

    /// Check if mailing exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete mailing by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted mailing by ID
    async fn restore(&self, id: &str) -> Result<Option<Mailing>>;

    /// List soft-deleted mailing entities
    async fn list_deleted(&self, params: MailingPaginationParams) -> Result<MailingPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save mailing entities
    async fn bulk_save(&self, entities: &[Mailing]) -> Result<Vec<Mailing>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
