//! Repository trait for MailingFilter aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the MailingFilter aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;

use crate::domain::entity::{MailingFilter, MailingTargetModel};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct MailingFilterPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl MailingFilterPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct MailingFilterPaginatedResult {
    pub data: Vec<MailingFilter>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct MailingFilterFilter {
    pub name: Option<String>,
    pub target_model: Option<MailingTargetModel>,
}

impl MailingFilterFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.name.is_some() || self.target_model.is_some()
    }
}

/// Repository trait for MailingFilter aggregate
///
/// This trait defines the persistence contract for MailingFilter entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait MailingFilterRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new mailing_filter entity
    async fn save(&self, entity: &MailingFilter) -> Result<MailingFilter>;

    /// Find mailing_filter by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<MailingFilter>>;

    /// Find all mailing_filter entities
    async fn find_all(&self) -> Result<Vec<MailingFilter>>;

    /// Update mailing_filter by ID
    async fn update(&self, id: &str, entity: &MailingFilter) -> Result<Option<MailingFilter>>;

    /// Delete mailing_filter by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List mailing_filter with pagination
    async fn list(&self, params: MailingFilterPaginationParams) -> Result<MailingFilterPaginatedResult>;

    /// List mailing_filter with pagination and filters
    async fn list_with_filters(&self, params: MailingFilterPaginationParams, filters: MailingFilterFilter) -> Result<MailingFilterPaginatedResult>;

    /// Count all mailing_filter entities
    async fn count(&self) -> Result<u64>;

    /// Count mailing_filter entities matching filters
    async fn count_with_filters(&self, filters: MailingFilterFilter) -> Result<u64>;

    /// Check if mailing_filter exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete mailing_filter by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted mailing_filter by ID
    async fn restore(&self, id: &str) -> Result<Option<MailingFilter>>;

    /// List soft-deleted mailing_filter entities
    async fn list_deleted(&self, params: MailingFilterPaginationParams) -> Result<MailingFilterPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save mailing_filter entities
    async fn bulk_save(&self, entities: &[MailingFilter]) -> Result<Vec<MailingFilter>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
