//! Repository trait for MailingAudience aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the MailingAudience aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;

use crate::domain::entity::MailingAudience;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct MailingAudiencePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl MailingAudiencePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct MailingAudiencePaginatedResult {
    pub data: Vec<MailingAudience>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct MailingAudienceFilter {
    pub name: Option<String>,
    pub active: Option<bool>,
    pub is_public: Option<bool>,
}

impl MailingAudienceFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.name.is_some() || self.active.is_some() || self.is_public.is_some()
    }
}

/// Repository trait for MailingAudience aggregate
///
/// This trait defines the persistence contract for MailingAudience entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait MailingAudienceRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new mailing_audience entity
    async fn save(&self, entity: &MailingAudience) -> Result<MailingAudience>;

    /// Find mailing_audience by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<MailingAudience>>;

    /// Find all mailing_audience entities
    async fn find_all(&self) -> Result<Vec<MailingAudience>>;

    /// Update mailing_audience by ID
    async fn update(&self, id: &str, entity: &MailingAudience) -> Result<Option<MailingAudience>>;

    /// Delete mailing_audience by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List mailing_audience with pagination
    async fn list(&self, params: MailingAudiencePaginationParams) -> Result<MailingAudiencePaginatedResult>;

    /// List mailing_audience with pagination and filters
    async fn list_with_filters(&self, params: MailingAudiencePaginationParams, filters: MailingAudienceFilter) -> Result<MailingAudiencePaginatedResult>;

    /// Count all mailing_audience entities
    async fn count(&self) -> Result<u64>;

    /// Count mailing_audience entities matching filters
    async fn count_with_filters(&self, filters: MailingAudienceFilter) -> Result<u64>;

    /// Check if mailing_audience exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete mailing_audience by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted mailing_audience by ID
    async fn restore(&self, id: &str) -> Result<Option<MailingAudience>>;

    /// List soft-deleted mailing_audience entities
    async fn list_deleted(&self, params: MailingAudiencePaginationParams) -> Result<MailingAudiencePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save mailing_audience entities
    async fn bulk_save(&self, entities: &[MailingAudience]) -> Result<Vec<MailingAudience>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
