//! Repository traits
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DDD Repository traits - define persistence contracts for aggregates.
//! Implementations should be in the infrastructure layer.


pub mod mailing_ab_test_repository;
pub mod mailing_audience_repository;
pub mod mailing_contact_repository;
pub mod mailing_subscription_repository;
pub mod opt_out_reason_repository;
pub mod mailing_repository;
pub mod mailing_trace_repository;
pub mod mailing_filter_repository;

// Re-exports
pub use mailing_ab_test_repository::{
    MailingAbTestRepository,
    MailingAbTestPaginationParams,
    MailingAbTestPaginatedResult,
    MailingAbTestFilter,
};
pub use mailing_audience_repository::{
    MailingAudienceRepository,
    MailingAudiencePaginationParams,
    MailingAudiencePaginatedResult,
    MailingAudienceFilter,
};
pub use mailing_contact_repository::{
    MailingContactRepository,
    MailingContactPaginationParams,
    MailingContactPaginatedResult,
    MailingContactFilter,
};
pub use mailing_subscription_repository::{
    MailingSubscriptionRepository,
    MailingSubscriptionPaginationParams,
    MailingSubscriptionPaginatedResult,
    MailingSubscriptionFilter,
};
pub use opt_out_reason_repository::{
    OptOutReasonRepository,
    OptOutReasonPaginationParams,
    OptOutReasonPaginatedResult,
    OptOutReasonFilter,
};
pub use mailing_repository::{
    MailingRepository,
    MailingPaginationParams,
    MailingPaginatedResult,
    MailingFilter,
};
pub use mailing_trace_repository::{
    MailingTraceRepository,
    MailingTracePaginationParams,
    MailingTracePaginatedResult,
    MailingTraceFilter,
};
pub use mailing_filter_repository::{
    MailingFilterRepository,
    MailingFilterPaginationParams,
    MailingFilterPaginatedResult,
    MailingFilterFilter,
};
