//! Repository for MailingAudience entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<MailingAudience, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::MailingAudience;

/// Table name for MailingAudience entities
pub const TABLE_NAME: &str = "mailing.mailing_audiences";

/// Repository for MailingAudience entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct MailingAudienceRepository(
    backbone_orm::GenericCrudRepository<MailingAudience, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for MailingAudienceRepository {
    type Target = backbone_orm::GenericCrudRepository<MailingAudience, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl MailingAudienceRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(MailingAudienceRepository, MailingAudience, soft_delete);
