//! Repository for MailingTrace entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<MailingTrace, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::MailingTrace;

/// Table name for MailingTrace entities
pub const TABLE_NAME: &str = "mailing.mailing_traces";

/// Repository for MailingTrace entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct MailingTraceRepository(
    backbone_orm::GenericCrudRepository<MailingTrace, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for MailingTraceRepository {
    type Target = backbone_orm::GenericCrudRepository<MailingTrace, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl MailingTraceRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(MailingTraceRepository, MailingTrace, soft_delete);
