//! Repository for MailingAbTest entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<MailingAbTest, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::MailingAbTest;

/// Table name for MailingAbTest entities
pub const TABLE_NAME: &str = "mailing.mailing_ab_tests";

/// Repository for MailingAbTest entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct MailingAbTestRepository(
    backbone_orm::GenericCrudRepository<MailingAbTest, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for MailingAbTestRepository {
    type Target = backbone_orm::GenericCrudRepository<MailingAbTest, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl MailingAbTestRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(MailingAbTestRepository, MailingAbTest, soft_delete);
