//! Repository implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Uses backbone-orm's `DatabaseOperations<T>` trait.

mod mailing_ab_test_repository;
mod mailing_audience_repository;
mod mailing_contact_repository;
mod mailing_subscription_repository;
mod opt_out_reason_repository;
mod mailing_repository;
mod mailing_trace_repository;
mod mailing_filter_repository;

// Custom persistence modules
// <<< CUSTOM
pub mod mailing_send_repository;
pub mod subscription_repository;
pub mod trace_repository;
// END CUSTOM

// Re-exports
pub use mailing_ab_test_repository::MailingAbTestRepository;
pub use mailing_audience_repository::MailingAudienceRepository;
pub use mailing_contact_repository::MailingContactRepository;
pub use mailing_subscription_repository::MailingSubscriptionRepository;
pub use opt_out_reason_repository::OptOutReasonRepository;
pub use mailing_repository::MailingRepository;
pub use mailing_trace_repository::MailingTraceRepository;
pub use mailing_filter_repository::MailingFilterRepository;

// Re-export backbone-orm types
pub use backbone_orm::repository::{
    DatabaseOperations, PostgresRepository,
    PaginationParams, PaginationInfo, PaginatedResult,
    FilterParams, FilterCondition, SortParams, SortDirection,
};

// Re-export custom persistence types
// <<< CUSTOM
pub use mailing_send_repository::{
    ClaimedMailing, CompiledDomain, DomainField, DomainOp, DomainTerm, MailingSendRepository,
    ResolvedRecipient,
};
pub use subscription_repository::{AudienceRecipient, SubscriptionRepository, SubscriptionRow};
pub use trace_repository::{MailingTraceCounts, TraceRepository, TraceRow};
// END CUSTOM
