//! Validator for Mailing entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Mailing>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::Mailing;

/// Validator type alias for Mailing entities.
pub type MailingValidator = EntityValidator<Mailing>;

/// Build a validator for Mailing with all schema-defined field rules.
pub fn mailing_validator() -> MailingValidator {
    EntityValidator::new()
        .rule(RequiredString::new("subject", |e: &Mailing| &e.subject))
        .rule(OptionalNotBlank::new("preview", |e: &Mailing| e.preview.as_deref()))
        .rule(RequiredString::new("body_html", |e: &Mailing| &e.body_html))
        .rule(RequiredString::new("email_from", |e: &Mailing| &e.email_from))
        .rule(OptionalNotBlank::new("reply_to", |e: &Mailing| e.reply_to.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
