//! Validator for MailingAbTest entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<MailingAbTest>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{RequiredString};
use crate::domain::entity::MailingAbTest;

/// Validator type alias for MailingAbTest entities.
pub type MailingAbTestValidator = EntityValidator<MailingAbTest>;

/// Build a validator for MailingAbTest with all schema-defined field rules.
pub fn mailing_ab_test_validator() -> MailingAbTestValidator {
    EntityValidator::new()
        .rule(RequiredString::new("sampling_seed", |e: &MailingAbTest| &e.sampling_seed))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
