//! Validator for MailingContact entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<MailingContact>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::MailingContact;

/// Validator type alias for MailingContact entities.
pub type MailingContactValidator = EntityValidator<MailingContact>;

/// Build a validator for MailingContact with all schema-defined field rules.
pub fn mailing_contact_validator() -> MailingContactValidator {
    EntityValidator::new()
        .rule(OptionalNotBlank::new("name", |e: &MailingContact| e.name.as_deref()))
        .rule(OptionalNotBlank::new("first_name", |e: &MailingContact| e.first_name.as_deref()))
        .rule(OptionalNotBlank::new("last_name", |e: &MailingContact| e.last_name.as_deref()))
        .rule(RequiredString::new("email", |e: &MailingContact| &e.email))
        .rule(OptionalNotBlank::new("company_name", |e: &MailingContact| e.company_name.as_deref()))
        .rule(OptionalNotBlank::new("country_code", |e: &MailingContact| e.country_code.as_deref()))
        .rule(OptionalNotBlank::new("phone", |e: &MailingContact| e.phone.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
