//! Validator for MailingTrace entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<MailingTrace>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::MailingTrace;

/// Validator type alias for MailingTrace entities.
pub type MailingTraceValidator = EntityValidator<MailingTrace>;

/// Build a validator for MailingTrace with all schema-defined field rules.
pub fn mailing_trace_validator() -> MailingTraceValidator {
    EntityValidator::new()
        .rule(RequiredString::new("recipient_model", |e: &MailingTrace| &e.recipient_model))
        .rule(RequiredString::new("recipient_email", |e: &MailingTrace| &e.recipient_email))
        .rule(OptionalNotBlank::new("message_id", |e: &MailingTrace| e.message_id.as_deref()))
        .rule(OptionalNotBlank::new("failure_reason", |e: &MailingTrace| e.failure_reason.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
