//! Validator for MailingFilter entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<MailingFilter>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{RequiredString};
use crate::domain::entity::MailingFilter;

/// Validator type alias for MailingFilter entities.
pub type MailingFilterValidator = EntityValidator<MailingFilter>;

/// Build a validator for MailingFilter with all schema-defined field rules.
pub fn mailing_filter_validator() -> MailingFilterValidator {
    EntityValidator::new()
        .rule(RequiredString::new("name", |e: &MailingFilter| &e.name))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
