//! Validator for MailingSubscription entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<MailingSubscription>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use crate::domain::entity::MailingSubscription;

/// Validator type alias for MailingSubscription entities.
pub type MailingSubscriptionValidator = EntityValidator<MailingSubscription>;

/// Build a validator for MailingSubscription with all schema-defined field rules.
pub fn mailing_subscription_validator() -> MailingSubscriptionValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
        // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
