//! Validator for MailingAudience entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<MailingAudience>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{RequiredString};
use crate::domain::entity::MailingAudience;

/// Validator type alias for MailingAudience entities.
pub type MailingAudienceValidator = EntityValidator<MailingAudience>;

/// Build a validator for MailingAudience with all schema-defined field rules.
pub fn mailing_audience_validator() -> MailingAudienceValidator {
    EntityValidator::new()
        .rule(RequiredString::new("name", |e: &MailingAudience| &e.name))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
