//! Entity validators
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::{ValidationError, ValidationErrors, ValidationResult, EntityValidator};

pub mod mailing_ab_test_validator;
pub mod mailing_audience_validator;
pub mod mailing_contact_validator;
pub mod mailing_subscription_validator;
pub mod opt_out_reason_validator;
pub mod mailing_validator;
pub mod mailing_trace_validator;
pub mod mailing_filter_validator;

pub use mailing_ab_test_validator::{MailingAbTestValidator, mailing_ab_test_validator};
pub use mailing_audience_validator::{MailingAudienceValidator, mailing_audience_validator};
pub use mailing_contact_validator::{MailingContactValidator, mailing_contact_validator};
pub use mailing_subscription_validator::{MailingSubscriptionValidator, mailing_subscription_validator};
pub use opt_out_reason_validator::{OptOutReasonValidator, opt_out_reason_validator};
pub use mailing_validator::{MailingValidator, mailing_validator};
pub use mailing_trace_validator::{MailingTraceValidator, mailing_trace_validator};
pub use mailing_filter_validator::{MailingFilterValidator, mailing_filter_validator};

// <<< CUSTOM
// END CUSTOM
