//! Validator for OptOutReason entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<OptOutReason>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{RequiredString};
use crate::domain::entity::OptOutReason;

/// Validator type alias for OptOutReason entities.
pub type OptOutReasonValidator = EntityValidator<OptOutReason>;

/// Build a validator for OptOutReason with all schema-defined field rules.
pub fn opt_out_reason_validator() -> OptOutReasonValidator {
    EntityValidator::new()
        .rule(RequiredString::new("name", |e: &OptOutReason| &e.name))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
