//! MailingSubscription API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the MailingSubscription CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// MAILINGSUBSCRIPTION TEST DATA GENERATOR
// ============================================================================

/// Test data generator for MailingSubscription
pub struct MailingSubscriptionTestData;

impl TestDataGenerator for MailingSubscriptionTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "contact_id": Uuid::new_v4().to_string(),
            "mailing_audience_id": Uuid::new_v4().to_string(),
            "opt_out": false,
            "opt_out_datetime": null,
            "opt_out_reason_id": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "contact_id": Uuid::new_v4().to_string(),
            "mailing_audience_id": Uuid::new_v4().to_string(),
            "opt_out": false,
            "opt_out_datetime": null,
            "opt_out_reason_id": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// MAILINGSUBSCRIPTION API TEST
// ============================================================================

/// MailingSubscription API test suite
pub struct MailingSubscriptionApiTest {
    inner: GenericCrudTest<MailingSubscriptionTestData>,
}

impl MailingSubscriptionApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/mailing_subscriptions", "MailingSubscription");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, MailingSubscriptionTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for MailingSubscriptionApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_mailing_subscription_crud() {
        let mut test = MailingSubscriptionApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add MailingSubscription specific tests here
// <<< CUSTOM TESTS END >>>
