//! MailingTrace API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the MailingTrace CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// MAILINGTRACE TEST DATA GENERATOR
// ============================================================================

/// Test data generator for MailingTrace
pub struct MailingTraceTestData;

impl TestDataGenerator for MailingTraceTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "trace_type": "mail",
            "is_test_trace": false,
            "mailing_id": Uuid::new_v4().to_string(),
            "campaign_id": null,
            "recipient_model": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "recipient_id": Uuid::new_v4().to_string(),
            "recipient_email": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "mail_id": null,
            "sms_uuid": null,
            "recipient_phone": null,
            "message_id": null,
            "trace_status": "outgoing",
            "failure_type": null,
            "failure_reason": null,
            "sent_datetime": null,
            "open_datetime": null,
            "reply_datetime": null,
            "links_click_datetime": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "trace_type": "mail",
            "is_test_trace": false,
            "mailing_id": Uuid::new_v4().to_string(),
            "campaign_id": null,
            "recipient_model": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "recipient_id": Uuid::new_v4().to_string(),
            "recipient_email": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "mail_id": null,
            "sms_uuid": null,
            "recipient_phone": null,
            "message_id": null,
            "trace_status": "outgoing",
            "failure_type": null,
            "failure_reason": null,
            "sent_datetime": null,
            "open_datetime": null,
            "reply_datetime": null,
            "links_click_datetime": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// MAILINGTRACE API TEST
// ============================================================================

/// MailingTrace API test suite
pub struct MailingTraceApiTest {
    inner: GenericCrudTest<MailingTraceTestData>,
}

impl MailingTraceApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/mailing_traces", "MailingTrace");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, MailingTraceTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for MailingTraceApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_mailing_trace_crud() {
        let mut test = MailingTraceApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add MailingTrace specific tests here
// <<< CUSTOM TESTS END >>>
