//! MailingContact API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the MailingContact CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// MAILINGCONTACT TEST DATA GENERATOR
// ============================================================================

/// Test data generator for MailingContact
pub struct MailingContactTestData;

impl TestDataGenerator for MailingContactTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "name": null,
            "first_name": null,
            "last_name": null,
            "email": format!("test{}@example.com", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "company_name": null,
            "country_code": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "name": null,
            "first_name": null,
            "last_name": null,
            "email": format!("test{}@example.com", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "company_name": null,
            "country_code": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// MAILINGCONTACT API TEST
// ============================================================================

/// MailingContact API test suite
pub struct MailingContactApiTest {
    inner: GenericCrudTest<MailingContactTestData>,
}

impl MailingContactApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/mailing_contacts", "MailingContact");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, MailingContactTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for MailingContactApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_mailing_contact_crud() {
        let mut test = MailingContactApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add MailingContact specific tests here
// <<< CUSTOM TESTS END >>>
