//! Mailing API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the Mailing CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// MAILING TEST DATA GENERATOR
// ============================================================================

/// Test data generator for Mailing
pub struct MailingTestData;

impl TestDataGenerator for MailingTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "subject": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "preview": null,
            "body_html": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "body_plaintext": null,
            "email_from": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "reply_to": null,
            "keep_archives": false,
            "state": "draft",
            "schedule_type": "immediate",
            "schedule_date": null,
            "sent_date": null,
            "mailing_type": "mail",
            "target_model": "mailing_contact",
            "mailing_domain": json!({}),
            "use_exclusion_list": false,
            "campaign_id": null,
            "medium_id": null,
            "source_id": null,
            "user_id": null,
            "ab_testing_enabled": false,
            "ab_testing_pc": 1,
            "ab_test_id": null,
            "kpi_mail_required": false,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "subject": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "preview": null,
            "body_html": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "body_plaintext": null,
            "email_from": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "reply_to": null,
            "keep_archives": false,
            "state": "draft",
            "schedule_type": "immediate",
            "schedule_date": null,
            "sent_date": null,
            "mailing_type": "mail",
            "target_model": "mailing_contact",
            "mailing_domain": json!({}),
            "use_exclusion_list": false,
            "campaign_id": null,
            "medium_id": null,
            "source_id": null,
            "user_id": null,
            "ab_testing_enabled": false,
            "ab_testing_pc": 1,
            "ab_test_id": null,
            "kpi_mail_required": false,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// MAILING API TEST
// ============================================================================

/// Mailing API test suite
pub struct MailingApiTest {
    inner: GenericCrudTest<MailingTestData>,
}

impl MailingApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/mailings", "Mailing");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, MailingTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for MailingApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_mailing_crud() {
        let mut test = MailingApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add Mailing specific tests here
// <<< CUSTOM TESTS END >>>
