//! MailingAbTest API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the MailingAbTest CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// MAILINGABTEST TEST DATA GENERATOR
// ============================================================================

/// Test data generator for MailingAbTest
pub struct MailingAbTestTestData;

impl TestDataGenerator for MailingAbTestTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "campaign_id": Uuid::new_v4().to_string(),
            "winner_selection": "manual",
            "winner_selection_sms": null,
            "promote_at": now,
            "completed": false,
            "winner_mailing_id": null,
            "sampling_seed": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "campaign_id": Uuid::new_v4().to_string(),
            "winner_selection": "manual",
            "winner_selection_sms": null,
            "promote_at": now,
            "completed": false,
            "winner_mailing_id": null,
            "sampling_seed": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// MAILINGABTEST API TEST
// ============================================================================

/// MailingAbTest API test suite
pub struct MailingAbTestApiTest {
    inner: GenericCrudTest<MailingAbTestTestData>,
}

impl MailingAbTestApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/mailing_ab_tests", "MailingAbTest");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, MailingAbTestTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for MailingAbTestApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_mailing_ab_test_crud() {
        let mut test = MailingAbTestApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add MailingAbTest specific tests here
// <<< CUSTOM TESTS END >>>
