//! Integration Test Implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Contains CRUD API tests for all entities.

pub mod crud_test_base;

pub mod mailing_ab_test_api_test;
pub mod mailing_audience_api_test;
pub mod mailing_contact_api_test;
pub mod mailing_subscription_api_test;
pub mod opt_out_reason_api_test;
pub mod mailing_api_test;
pub mod mailing_trace_api_test;
pub mod mailing_filter_api_test;

// Re-exports for convenience
pub use crud_test_base::*;
pub use mailing_ab_test_api_test::*;
pub use mailing_audience_api_test::*;
pub use mailing_contact_api_test::*;
pub use mailing_subscription_api_test::*;
pub use opt_out_reason_api_test::*;
pub use mailing_api_test::*;
pub use mailing_trace_api_test::*;
pub use mailing_filter_api_test::*;
