//! OptOutReason API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the OptOutReason CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// OPTOUTREASON TEST DATA GENERATOR
// ============================================================================

/// Test data generator for OptOutReason
pub struct OptOutReasonTestData;

impl TestDataGenerator for OptOutReasonTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "sequence": 1,
            "is_feedback": false,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "sequence": 1,
            "is_feedback": false,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// OPTOUTREASON API TEST
// ============================================================================

/// OptOutReason API test suite
pub struct OptOutReasonApiTest {
    inner: GenericCrudTest<OptOutReasonTestData>,
}

impl OptOutReasonApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/mailing_opt_out_reasons", "OptOutReason");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, OptOutReasonTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for OptOutReasonApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_opt_out_reason_crud() {
        let mut test = OptOutReasonApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add OptOutReason specific tests here
// <<< CUSTOM TESTS END >>>
