//! Mailing Module Exports
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module defines the public API that Mailing exposes to other modules.
//! Other modules should ONLY depend on types defined here, not internal types.
//!
//! ## Usage from other modules
//!
//! ```text
//! use mailing::exports::{MailingAbTestDto};
//! ```

mod types;
mod services;
mod events;

// Re-export all public types
pub use types::*;
pub use services::*;
pub use events::*;

// ============================================================================
// EXPORT SUMMARY
// ============================================================================

/// Summary of what this module exports
///
/// ## Public Types
/// - `MailingAbTestDto` - Data transfer object for MailingAbTest
/// - `MailingAbTestSummary` - Summary view of MailingAbTest
/// - `MailingAbTestId` - Type-safe ID wrapper
/// - `MailingAudienceDto` - Data transfer object for MailingAudience
/// - `MailingAudienceSummary` - Summary view of MailingAudience
/// - `MailingAudienceId` - Type-safe ID wrapper
/// - `MailingContactDto` - Data transfer object for MailingContact
/// - `MailingContactSummary` - Summary view of MailingContact
/// - `MailingContactId` - Type-safe ID wrapper
/// - `MailingSubscriptionDto` - Data transfer object for MailingSubscription
/// - `MailingSubscriptionSummary` - Summary view of MailingSubscription
/// - `MailingSubscriptionId` - Type-safe ID wrapper
/// - `OptOutReasonDto` - Data transfer object for OptOutReason
/// - `OptOutReasonSummary` - Summary view of OptOutReason
/// - `OptOutReasonId` - Type-safe ID wrapper
/// - `MailingDto` - Data transfer object for Mailing
/// - `MailingSummary` - Summary view of Mailing
/// - `MailingId` - Type-safe ID wrapper
/// - `MailingTraceDto` - Data transfer object for MailingTrace
/// - `MailingTraceSummary` - Summary view of MailingTrace
/// - `MailingTraceId` - Type-safe ID wrapper
/// - `MailingFilterDto` - Data transfer object for MailingFilter
/// - `MailingFilterSummary` - Summary view of MailingFilter
/// - `MailingFilterId` - Type-safe ID wrapper
///
/// ## Public Events
/// - `MailingAbTestCreatedEvent` - Published when MailingAbTest is created
/// - `MailingAbTestUpdatedEvent` - Published when MailingAbTest is updated
/// - `MailingAbTestDeletedEvent` - Published when MailingAbTest is deleted
/// - `MailingAudienceCreatedEvent` - Published when MailingAudience is created
/// - `MailingAudienceUpdatedEvent` - Published when MailingAudience is updated
/// - `MailingAudienceDeletedEvent` - Published when MailingAudience is deleted
/// - `MailingContactCreatedEvent` - Published when MailingContact is created
/// - `MailingContactUpdatedEvent` - Published when MailingContact is updated
/// - `MailingContactDeletedEvent` - Published when MailingContact is deleted
/// - `MailingSubscriptionCreatedEvent` - Published when MailingSubscription is created
/// - `MailingSubscriptionUpdatedEvent` - Published when MailingSubscription is updated
/// - `MailingSubscriptionDeletedEvent` - Published when MailingSubscription is deleted
/// - `OptOutReasonCreatedEvent` - Published when OptOutReason is created
/// - `OptOutReasonUpdatedEvent` - Published when OptOutReason is updated
/// - `OptOutReasonDeletedEvent` - Published when OptOutReason is deleted
/// - `MailingCreatedEvent` - Published when Mailing is created
/// - `MailingUpdatedEvent` - Published when Mailing is updated
/// - `MailingDeletedEvent` - Published when Mailing is deleted
/// - `MailingTraceCreatedEvent` - Published when MailingTrace is created
/// - `MailingTraceUpdatedEvent` - Published when MailingTrace is updated
/// - `MailingTraceDeletedEvent` - Published when MailingTrace is deleted
/// - `MailingFilterCreatedEvent` - Published when MailingFilter is created
/// - `MailingFilterUpdatedEvent` - Published when MailingFilter is updated
/// - `MailingFilterDeletedEvent` - Published when MailingFilter is deleted
pub struct ExportSummary;
