//! Mailing REST handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Uses Axum and backbone-core's BackboneCrudHandler for all 12 CRUD endpoints.

use std::collections::HashMap;
use std::sync::Arc;

use axum::Router;
use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

// Backbone framework imports
use backbone_core::http::{ApiResponse, BackboneCrudHandler};

// Auth integration (optional)
#[cfg(feature = "auth")]
use backbone_auth::middleware::AuthContext;
#[cfg(feature = "auth")]
use backbone_auth::AuthMiddleware;

// Domain imports
use crate::domain::entity::*;
use crate::application::service::{MailingService, ServiceError};

// DTO imports
use crate::presentation::dto::{CreateMailingDto, UpdateMailingDto, PatchMailingDto, MailingResponseDto};

use crate::domain::state_machine::{mailing_stateState, mailing_stateStateMachine, mailing_stateTransition};

/// Application error type
#[derive(Debug, thiserror::Error)]
pub enum MailingError {
    #[error("Not found: {0}")]
    NotFound(String),
    #[error("Validation error: {0}")]
    Validation(String),
    #[error("Database error: {0}")]
    Database(String),
    #[error("Internal error: {0}")]
    Internal(String),
}

impl From<ServiceError> for MailingError {
    fn from(err: ServiceError) -> Self {
        match err {
            ServiceError::NotFound => Self::NotFound(err.to_string()),
            ServiceError::Validation(ref msg) => Self::Validation(msg.clone()),
            ServiceError::AlreadyExists(ref msg) => Self::Validation(msg.clone()),
            ServiceError::Repository(ref e) => Self::Database(e.to_string()),
            ServiceError::Internal(ref msg) => Self::Internal(msg.clone()),
        }
    }
}

impl axum::response::IntoResponse for MailingError {
    fn into_response(self) -> axum::response::Response {
        use axum::http::StatusCode;
        use axum::Json;

        let (status, code) = match &self {
            Self::NotFound(_) => (StatusCode::NOT_FOUND, "MAILING_NOT_FOUND"),
            Self::Validation(_) => (StatusCode::BAD_REQUEST, "MAILING_VALIDATION_ERROR"),
            Self::Database(_) => (StatusCode::INTERNAL_SERVER_ERROR, "MAILING_DATABASE_ERROR"),
            Self::Internal(_) => (StatusCode::INTERNAL_SERVER_ERROR, "MAILING_INTERNAL_ERROR"),
        };

        let body = serde_json::json!({
            "success": false,
            "error": code,
            "message": self.to_string(),
        });

        (status, Json(body)).into_response()
    }
}

// =============================================================================
// Route Configuration
// =============================================================================

/// Create Axum router with all 16 Backbone endpoints for Mailing.
///
/// # Routes
///
/// | Method | Path | Description |
/// |--------|------|-------------|
/// | GET | /mailings | List with pagination |
/// | POST | /mailings | Create new |
/// | GET | /mailings/:id | Get by ID |
/// | PUT | /mailings/:id | Full update |
/// | PATCH | /mailings/:id | Partial update |
/// | DELETE | /mailings/:id | Soft delete |
/// | POST | /mailings/bulk | Bulk create |
/// | POST | /mailings/upsert | Upsert |
/// | GET | /mailings/trash | List deleted |
/// | POST | /mailings/:id/restore | Restore |
/// | DELETE | /mailings/empty | Empty trash |
/// | GET | /mailings/:id/deleted | Get deleted by ID |
/// | DELETE | /mailings/trash/:id | Permanent delete from trash |
/// | GET | /mailings/count | Count active entities |
/// | GET | /mailings/trash/count | Count deleted entities |
///
/// # Example
///
/// ```text
/// let service = Arc::new(MailingService::with_repository(repository));
/// let router = create_mailing_routes(service);
/// ```
pub fn create_mailing_routes(service: Arc<MailingService>) -> Router {
    BackboneCrudHandler::<MailingService, Mailing, CreateMailingDto, UpdateMailingDto, MailingResponseDto>::routes(
        service,
        "/mailings",
    )
}

/// Create Axum router with only the read (GET) endpoints for Mailing.
///
/// Safe for public, unauthenticated exposure (e.g., reference data).
/// Mutations must be served separately via `create_mailing_write_routes`,
/// typically wrapped in an auth middleware layer.
pub fn create_mailing_read_routes(service: Arc<MailingService>) -> Router {
    BackboneCrudHandler::<MailingService, Mailing, CreateMailingDto, UpdateMailingDto, MailingResponseDto>::read_routes(
        service,
        "/mailings",
    )
}

/// Create Axum router with only the write (mutation) endpoints for Mailing.
///
/// These routes must NOT be publicly exposed. Wrap them with an auth
/// middleware before nesting into the application router.
///
/// # This is unguarded generic CRUD, not a validated write path
///
/// These are plain create/update/patch/delete mutations over the entity row —
/// they bypass all business invariants. If the module exposes a validated write
/// service (e.g. a command router over its domain engine), serve THAT instead
/// for any mutation that must respect domain rules.
pub fn create_mailing_write_routes(service: Arc<MailingService>) -> Router {
    BackboneCrudHandler::<MailingService, Mailing, CreateMailingDto, UpdateMailingDto, MailingResponseDto>::write_routes(
        service,
        "/mailings",
    )
}

/// Create authenticated routes with auth middleware.
///
/// Requires the `auth` feature flag. The `AuthMiddleware` implementation
/// is responsible for extracting and validating tokens, then providing
/// an `AuthContext` via request extensions.
#[cfg(feature = "auth")]
pub fn create_protected_mailing_routes<A: AuthMiddleware + Send + Sync + 'static>(
    service: Arc<MailingService>,
    auth: Arc<A>,
) -> Router {
    use axum::middleware;
    use axum::response::IntoResponse;

    let auth_layer = auth.clone();
    create_mailing_routes(service)
        .layer(middleware::from_fn(move |mut req: axum::extract::Request, next: axum::middleware::Next| {
            let auth = auth_layer.clone();
            async move {
                let token = req.headers()
                    .get(axum::http::header::AUTHORIZATION)
                    .and_then(|h| h.to_str().ok())
                    .and_then(|raw| raw.strip_prefix("Bearer ").or_else(|| raw.strip_prefix("bearer ")))
                    .unwrap_or("");
                match auth.authenticate(token).await {
                    Ok(ctx) => {
                        req.extensions_mut().insert(ctx);
                        next.run(req).await
                    }
                    Err(_) => {
                        (axum::http::StatusCode::UNAUTHORIZED,
                         axum::Json(serde_json::json!({
                             "success": false,
                             "error": "unauthorized",
                             "message": "Authentication required"
                         }))
                        ).into_response()
                    }
                }
            }
        }))
}

// =============================================================================
// State Transition Handlers
// =============================================================================

/// Execute launch transition on a Mailing.
///
/// POST /mailings/:id/transitions/launch
pub async fn launch_transition(
    axum::extract::State(service): axum::extract::State<Arc<MailingService>>,
    axum::extract::Path(id): axum::extract::Path<String>,
    #[cfg(feature = "auth")] axum::Extension(auth): axum::Extension<AuthContext>,
) -> impl axum::response::IntoResponse {
    use axum::{http::StatusCode, Json};

    // Get current entity
    let entity = match service.get_by_id(&id).await {
        Ok(Some(e)) => e,
        Ok(None) => return (StatusCode::NOT_FOUND, Json(ApiResponse::<MailingResponseDto>::not_found("Mailing", &id))),
        Err(e) => return (StatusCode::INTERNAL_SERVER_ERROR, Json(ApiResponse::<MailingResponseDto>::error(e.to_string()))),
    };

    // Check permission (if auth enabled)
    #[cfg(feature = "auth")]
    {
        let allowed_roles = mailing_stateTransition::Launch.allowed_roles();
        let has_specific_perm = auth.permissions.iter().any(|p| p == "mailing:transition:launch");
        let has_update_perm = auth.permissions.iter().any(|p| p == "mailing:update");
        if !has_specific_perm && !has_update_perm {
            return (StatusCode::FORBIDDEN, Json(ApiResponse::<MailingResponseDto>::error("Insufficient permissions for launch transition")));
        }
    }

    // Create state machine from entity's actual status and validate transition
    let current_state: mailing_stateState = entity.state.to_string().parse()
        .unwrap_or(mailing_stateState::default());
    let sm = mailing_stateStateMachine::from_state(current_state);
    if !sm.can_transition(mailing_stateTransition::Launch) {
        return (StatusCode::BAD_REQUEST, Json(ApiResponse::<MailingResponseDto>::error("Transition not allowed from current state")));
    }

    // Apply transition via partial update
    let mut fields: HashMap<String, serde_json::Value> = HashMap::new();
    fields.insert("state".to_string(), serde_json::Value::String("InQueue".to_string()));

    match service.partial_update(&id, fields).await {
        Ok(Some(updated)) => {
            let response: MailingResponseDto = updated.into();
            (StatusCode::OK, Json(ApiResponse::ok(response)))
        }
        Ok(None) => (StatusCode::NOT_FOUND, Json(ApiResponse::<MailingResponseDto>::not_found("Mailing", &id))),
        Err(e) => (StatusCode::INTERNAL_SERVER_ERROR, Json(ApiResponse::<MailingResponseDto>::error(e.to_string()))),
    }
}

/// Execute pickup transition on a Mailing.
///
/// POST /mailings/:id/transitions/pickup
pub async fn pickup_transition(
    axum::extract::State(service): axum::extract::State<Arc<MailingService>>,
    axum::extract::Path(id): axum::extract::Path<String>,
    #[cfg(feature = "auth")] axum::Extension(auth): axum::Extension<AuthContext>,
) -> impl axum::response::IntoResponse {
    use axum::{http::StatusCode, Json};

    // Get current entity
    let entity = match service.get_by_id(&id).await {
        Ok(Some(e)) => e,
        Ok(None) => return (StatusCode::NOT_FOUND, Json(ApiResponse::<MailingResponseDto>::not_found("Mailing", &id))),
        Err(e) => return (StatusCode::INTERNAL_SERVER_ERROR, Json(ApiResponse::<MailingResponseDto>::error(e.to_string()))),
    };

    // Check permission (if auth enabled)
    #[cfg(feature = "auth")]
    {
        let allowed_roles = mailing_stateTransition::Pickup.allowed_roles();
        let has_specific_perm = auth.permissions.iter().any(|p| p == "mailing:transition:pickup");
        let has_update_perm = auth.permissions.iter().any(|p| p == "mailing:update");
        if !has_specific_perm && !has_update_perm {
            return (StatusCode::FORBIDDEN, Json(ApiResponse::<MailingResponseDto>::error("Insufficient permissions for pickup transition")));
        }
    }

    // Create state machine from entity's actual status and validate transition
    let current_state: mailing_stateState = entity.state.to_string().parse()
        .unwrap_or(mailing_stateState::default());
    let sm = mailing_stateStateMachine::from_state(current_state);
    if !sm.can_transition(mailing_stateTransition::Pickup) {
        return (StatusCode::BAD_REQUEST, Json(ApiResponse::<MailingResponseDto>::error("Transition not allowed from current state")));
    }

    // Apply transition via partial update
    let mut fields: HashMap<String, serde_json::Value> = HashMap::new();
    fields.insert("state".to_string(), serde_json::Value::String("Sending".to_string()));

    match service.partial_update(&id, fields).await {
        Ok(Some(updated)) => {
            let response: MailingResponseDto = updated.into();
            (StatusCode::OK, Json(ApiResponse::ok(response)))
        }
        Ok(None) => (StatusCode::NOT_FOUND, Json(ApiResponse::<MailingResponseDto>::not_found("Mailing", &id))),
        Err(e) => (StatusCode::INTERNAL_SERVER_ERROR, Json(ApiResponse::<MailingResponseDto>::error(e.to_string()))),
    }
}

/// Execute complete transition on a Mailing.
///
/// POST /mailings/:id/transitions/complete
pub async fn complete_transition(
    axum::extract::State(service): axum::extract::State<Arc<MailingService>>,
    axum::extract::Path(id): axum::extract::Path<String>,
    #[cfg(feature = "auth")] axum::Extension(auth): axum::Extension<AuthContext>,
) -> impl axum::response::IntoResponse {
    use axum::{http::StatusCode, Json};

    // Get current entity
    let entity = match service.get_by_id(&id).await {
        Ok(Some(e)) => e,
        Ok(None) => return (StatusCode::NOT_FOUND, Json(ApiResponse::<MailingResponseDto>::not_found("Mailing", &id))),
        Err(e) => return (StatusCode::INTERNAL_SERVER_ERROR, Json(ApiResponse::<MailingResponseDto>::error(e.to_string()))),
    };

    // Check permission (if auth enabled)
    #[cfg(feature = "auth")]
    {
        let allowed_roles = mailing_stateTransition::Complete.allowed_roles();
        let has_specific_perm = auth.permissions.iter().any(|p| p == "mailing:transition:complete");
        let has_update_perm = auth.permissions.iter().any(|p| p == "mailing:update");
        if !has_specific_perm && !has_update_perm {
            return (StatusCode::FORBIDDEN, Json(ApiResponse::<MailingResponseDto>::error("Insufficient permissions for complete transition")));
        }
    }

    // Create state machine from entity's actual status and validate transition
    let current_state: mailing_stateState = entity.state.to_string().parse()
        .unwrap_or(mailing_stateState::default());
    let sm = mailing_stateStateMachine::from_state(current_state);
    if !sm.can_transition(mailing_stateTransition::Complete) {
        return (StatusCode::BAD_REQUEST, Json(ApiResponse::<MailingResponseDto>::error("Transition not allowed from current state")));
    }

    // Apply transition via partial update
    let mut fields: HashMap<String, serde_json::Value> = HashMap::new();
    fields.insert("state".to_string(), serde_json::Value::String("Done".to_string()));

    match service.partial_update(&id, fields).await {
        Ok(Some(updated)) => {
            let response: MailingResponseDto = updated.into();
            (StatusCode::OK, Json(ApiResponse::ok(response)))
        }
        Ok(None) => (StatusCode::NOT_FOUND, Json(ApiResponse::<MailingResponseDto>::not_found("Mailing", &id))),
        Err(e) => (StatusCode::INTERNAL_SERVER_ERROR, Json(ApiResponse::<MailingResponseDto>::error(e.to_string()))),
    }
}

/// Execute complete_empty transition on a Mailing.
///
/// POST /mailings/:id/transitions/complete_empty
pub async fn complete_empty_transition(
    axum::extract::State(service): axum::extract::State<Arc<MailingService>>,
    axum::extract::Path(id): axum::extract::Path<String>,
    #[cfg(feature = "auth")] axum::Extension(auth): axum::Extension<AuthContext>,
) -> impl axum::response::IntoResponse {
    use axum::{http::StatusCode, Json};

    // Get current entity
    let entity = match service.get_by_id(&id).await {
        Ok(Some(e)) => e,
        Ok(None) => return (StatusCode::NOT_FOUND, Json(ApiResponse::<MailingResponseDto>::not_found("Mailing", &id))),
        Err(e) => return (StatusCode::INTERNAL_SERVER_ERROR, Json(ApiResponse::<MailingResponseDto>::error(e.to_string()))),
    };

    // Check permission (if auth enabled)
    #[cfg(feature = "auth")]
    {
        let allowed_roles = mailing_stateTransition::CompleteEmpty.allowed_roles();
        let has_specific_perm = auth.permissions.iter().any(|p| p == "mailing:transition:complete_empty");
        let has_update_perm = auth.permissions.iter().any(|p| p == "mailing:update");
        if !has_specific_perm && !has_update_perm {
            return (StatusCode::FORBIDDEN, Json(ApiResponse::<MailingResponseDto>::error("Insufficient permissions for complete_empty transition")));
        }
    }

    // Create state machine from entity's actual status and validate transition
    let current_state: mailing_stateState = entity.state.to_string().parse()
        .unwrap_or(mailing_stateState::default());
    let sm = mailing_stateStateMachine::from_state(current_state);
    if !sm.can_transition(mailing_stateTransition::CompleteEmpty) {
        return (StatusCode::BAD_REQUEST, Json(ApiResponse::<MailingResponseDto>::error("Transition not allowed from current state")));
    }

    // Apply transition via partial update
    let mut fields: HashMap<String, serde_json::Value> = HashMap::new();
    fields.insert("state".to_string(), serde_json::Value::String("Done".to_string()));

    match service.partial_update(&id, fields).await {
        Ok(Some(updated)) => {
            let response: MailingResponseDto = updated.into();
            (StatusCode::OK, Json(ApiResponse::ok(response)))
        }
        Ok(None) => (StatusCode::NOT_FOUND, Json(ApiResponse::<MailingResponseDto>::not_found("Mailing", &id))),
        Err(e) => (StatusCode::INTERNAL_SERVER_ERROR, Json(ApiResponse::<MailingResponseDto>::error(e.to_string()))),
    }
}

/// Execute cancel transition on a Mailing.
///
/// POST /mailings/:id/transitions/cancel
pub async fn cancel_transition(
    axum::extract::State(service): axum::extract::State<Arc<MailingService>>,
    axum::extract::Path(id): axum::extract::Path<String>,
    #[cfg(feature = "auth")] axum::Extension(auth): axum::Extension<AuthContext>,
) -> impl axum::response::IntoResponse {
    use axum::{http::StatusCode, Json};

    // Get current entity
    let entity = match service.get_by_id(&id).await {
        Ok(Some(e)) => e,
        Ok(None) => return (StatusCode::NOT_FOUND, Json(ApiResponse::<MailingResponseDto>::not_found("Mailing", &id))),
        Err(e) => return (StatusCode::INTERNAL_SERVER_ERROR, Json(ApiResponse::<MailingResponseDto>::error(e.to_string()))),
    };

    // Check permission (if auth enabled)
    #[cfg(feature = "auth")]
    {
        let allowed_roles = mailing_stateTransition::Cancel.allowed_roles();
        let has_specific_perm = auth.permissions.iter().any(|p| p == "mailing:transition:cancel");
        let has_update_perm = auth.permissions.iter().any(|p| p == "mailing:update");
        if !has_specific_perm && !has_update_perm {
            return (StatusCode::FORBIDDEN, Json(ApiResponse::<MailingResponseDto>::error("Insufficient permissions for cancel transition")));
        }
    }

    // Create state machine from entity's actual status and validate transition
    let current_state: mailing_stateState = entity.state.to_string().parse()
        .unwrap_or(mailing_stateState::default());
    let sm = mailing_stateStateMachine::from_state(current_state);
    if !sm.can_transition(mailing_stateTransition::Cancel) {
        return (StatusCode::BAD_REQUEST, Json(ApiResponse::<MailingResponseDto>::error("Transition not allowed from current state")));
    }

    // Apply transition via partial update
    let mut fields: HashMap<String, serde_json::Value> = HashMap::new();
    fields.insert("state".to_string(), serde_json::Value::String("Draft".to_string()));

    match service.partial_update(&id, fields).await {
        Ok(Some(updated)) => {
            let response: MailingResponseDto = updated.into();
            (StatusCode::OK, Json(ApiResponse::ok(response)))
        }
        Ok(None) => (StatusCode::NOT_FOUND, Json(ApiResponse::<MailingResponseDto>::not_found("Mailing", &id))),
        Err(e) => (StatusCode::INTERNAL_SERVER_ERROR, Json(ApiResponse::<MailingResponseDto>::error(e.to_string()))),
    }
}

/// Execute retry_failed transition on a Mailing.
///
/// POST /mailings/:id/transitions/retry_failed
pub async fn retry_failed_transition(
    axum::extract::State(service): axum::extract::State<Arc<MailingService>>,
    axum::extract::Path(id): axum::extract::Path<String>,
    #[cfg(feature = "auth")] axum::Extension(auth): axum::Extension<AuthContext>,
) -> impl axum::response::IntoResponse {
    use axum::{http::StatusCode, Json};

    // Get current entity
    let entity = match service.get_by_id(&id).await {
        Ok(Some(e)) => e,
        Ok(None) => return (StatusCode::NOT_FOUND, Json(ApiResponse::<MailingResponseDto>::not_found("Mailing", &id))),
        Err(e) => return (StatusCode::INTERNAL_SERVER_ERROR, Json(ApiResponse::<MailingResponseDto>::error(e.to_string()))),
    };

    // Check permission (if auth enabled)
    #[cfg(feature = "auth")]
    {
        let allowed_roles = mailing_stateTransition::RetryFailed.allowed_roles();
        let has_specific_perm = auth.permissions.iter().any(|p| p == "mailing:transition:retry_failed");
        let has_update_perm = auth.permissions.iter().any(|p| p == "mailing:update");
        if !has_specific_perm && !has_update_perm {
            return (StatusCode::FORBIDDEN, Json(ApiResponse::<MailingResponseDto>::error("Insufficient permissions for retry_failed transition")));
        }
    }

    // Create state machine from entity's actual status and validate transition
    let current_state: mailing_stateState = entity.state.to_string().parse()
        .unwrap_or(mailing_stateState::default());
    let sm = mailing_stateStateMachine::from_state(current_state);
    if !sm.can_transition(mailing_stateTransition::RetryFailed) {
        return (StatusCode::BAD_REQUEST, Json(ApiResponse::<MailingResponseDto>::error("Transition not allowed from current state")));
    }

    // Apply transition via partial update
    let mut fields: HashMap<String, serde_json::Value> = HashMap::new();
    fields.insert("state".to_string(), serde_json::Value::String("InQueue".to_string()));

    match service.partial_update(&id, fields).await {
        Ok(Some(updated)) => {
            let response: MailingResponseDto = updated.into();
            (StatusCode::OK, Json(ApiResponse::ok(response)))
        }
        Ok(None) => (StatusCode::NOT_FOUND, Json(ApiResponse::<MailingResponseDto>::not_found("Mailing", &id))),
        Err(e) => (StatusCode::INTERNAL_SERVER_ERROR, Json(ApiResponse::<MailingResponseDto>::error(e.to_string()))),
    }
}

/// Create routes for state transitions.
pub fn create_mailing_transition_routes(service: Arc<MailingService>) -> Router {
    use axum::routing::post;

    Router::new()
        .route("/mailings/:id/transitions/launch", post(launch_transition))
        .route("/mailings/:id/transitions/pickup", post(pickup_transition))
        .route("/mailings/:id/transitions/complete", post(complete_transition))
        .route("/mailings/:id/transitions/complete_empty", post(complete_empty_transition))
        .route("/mailings/:id/transitions/cancel", post(cancel_transition))
        .route("/mailings/:id/transitions/retry_failed", post(retry_failed_transition))
        .with_state(service)
}
