//! HTTP handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These handlers use Axum and backbone-core's BackboneCrudHandler
//! to provide all 12 standard Backbone CRUD endpoints.

pub mod mailing_ab_test_handler;
pub mod mailing_audience_handler;
pub mod mailing_contact_handler;
pub mod mailing_subscription_handler;
pub mod opt_out_reason_handler;
pub mod mailing_handler;
pub mod mailing_trace_handler;
pub mod mailing_filter_handler;

// <<< CUSTOM
pub mod trace_routes;
// END CUSTOM

// Re-exports
pub use mailing_ab_test_handler::{create_mailing_ab_test_routes, create_mailing_ab_test_read_routes, create_mailing_ab_test_write_routes};
pub use mailing_audience_handler::{create_mailing_audience_routes, create_mailing_audience_read_routes, create_mailing_audience_write_routes};
pub use mailing_contact_handler::{create_mailing_contact_routes, create_mailing_contact_read_routes, create_mailing_contact_write_routes};
pub use mailing_subscription_handler::{create_mailing_subscription_routes, create_mailing_subscription_read_routes, create_mailing_subscription_write_routes};
pub use opt_out_reason_handler::{create_opt_out_reason_routes, create_opt_out_reason_read_routes, create_opt_out_reason_write_routes};
pub use mailing_handler::{create_mailing_routes, create_mailing_read_routes, create_mailing_write_routes};
pub use mailing_trace_handler::{create_mailing_trace_routes, create_mailing_trace_read_routes, create_mailing_trace_write_routes};
pub use mailing_filter_handler::{create_mailing_filter_routes, create_mailing_filter_read_routes, create_mailing_filter_write_routes};
// <<< CUSTOM
pub use trace_routes::{public_composer, public_trace_routes};
// END CUSTOM
